### ISSUE TITLE
Help needed to send "Moved Temporarily"

### ISSUE THREAD

**Issue by zeeshanfaisal** [siniypin/pjsip4net#101]
Hi 

I want to send 302 code(Divert Call) with new contact header in call hangup.
i successfully sent 302 but unable to set/send new Contact header through Pjsua_msg_data.
can you please tell how to do this.

Regards
Zeeshan

**Comment by siniypin** [comment]
Hi, this should be it: https://gist.github.com/siniypin/7504504

**Comment by zeeshanfaisal** [comment]
Thanks for the reply. Basically i want to transfer a call before answering it. The PABX I m using not permitting me to transfer a call while in ringing-in state.
I have tried this using a third party soft phone which successfully redirect call and by examining wireshark traces I noticed that soft phone send 302 status and new destination in contact header.
Can you please send a code snippet for how to use hdr_list in pjsua_msg_data strict.

**Comment by siniypin** [comment]
Probably this issue sheds some light https://github.com/siniypin/pjsip4net/issues/102#issuecomment-498666748.
