### ISSUE TITLE
Echo on outgoing calls

### ISSUE THREAD

**Issue by rndthoughts** [siniypin/pjsip4net#104]
**Describe the bug**
When making outgoing calls, the caller can hear themselves speaking a second or so after they have spoken.  When calling in from an external device (e.g. mobile phone) this echo does not happen.

**To Reproduce**

1.  Dial an outgoing number.
2.  Callee picks up.
3.  Caller can hear their own voice repeated back down the audio output channel.

**Expected behavior**
Caller should not be able to hear themselves played back down the audio channel

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Windows 10
 - NAT -> Internet -> NAT
 - Latest

**App configuration (please complete the following information):**
```
  <sipua srtp="Disabled" secureSignaling="0" logMessages="true" logLevel="5" traceAndDebug="false" autoAnswer="false" autoRecording="false" autoConference="false" maxCalls="5">
    <sipTransport type="udp" Port="5080" />
    <networkSettings natInSDP="true" forceLooseRoute="false">
      <turn enabled="false" server="" type="udp" userName="" password="" realm="" />
      <ice enabled="false" noRTCP="false" />
    </networkSettings>
    <media isVADEnabled="true" />
  </sipua>
```

**Additional context**
Only happens when the caller is calling out using this library to either an external or internal number.

**Comment by siniypin** [comment]
Hi, did you play around with Echo Canceller options that are controlled with [MediaConfig](https://github.com/siniypin/pjsip4net/blob/31bb2d92f1c5700f4e29b1b1284d4b2333ca0035/pjsip4net.Core/Data/MediaConfig.cs#L23)?  

You can set it with values found in [pjmedia_echo_flag](https://github.com/siniypin/pjsip4net/blob/31bb2d92f1c5700f4e29b1b1284d4b2333ca0035/pjsip.Interop/Interop.cs#L7071) enum. Give a PJMEDIA_ECHO_SPEEX a try.  

More info here: https://www.pjsip.org/docs/latest-1/pjsip/docs/html/structpjsua__media__config.htm#a734653d7e5d075984b9a51f053ded879

**Comment by siniypin** [comment]
Also try increasing [EcTailLen](https://github.com/siniypin/pjsip4net/blob/31bb2d92f1c5700f4e29b1b1284d4b2333ca0035/pjsip4net.Core/Data/MediaConfig.cs#L24)

**Comment by rndthoughts** [comment]
When i set either of those two properties (e.g. ecOptions):

` <media isVADEnabled="true" ecOptions="1" />`

It results in:

![image](https://user-images.githubusercontent.com/4190823/60880062-c0535380-a23a-11e9-885e-bffa4f9071b3.png)

**Comment by siniypin** [comment]
1. It seems unrelated as there is smth running on one of the ports you app is using. 
2. I don't think you can set ecOptions with xml config. It simply is not there: https://github.com/siniypin/pjsip4net/blob/master/pjsip4net/Configuration/MediaConfigurationElement.cs#L30

**Comment by siniypin** [comment]
For some reason I think setting EcTailLen to 500 ms may solve the problem.

**Comment by rndthoughts** [comment]
Thanks for the pointers - I think the error is misleading me because of the missing automapped properties not existing.  When the configuration is loaded and ecOptions is being mapped to a non-existant property it throws:

` System.Configuration.ConfigurationErrorsException: 'Unrecognized attribute 'ecOptions'. Note that attribute names are case-sensitive.`

This then causes configuration loading to fail hence the PjsipErrorException.

**Comment by siniypin** [comment]
Yep, you can manipulate config props that aren't available with xml .config during a creation of user agent as in the following example: https://gist.github.com/siniypin/7860386

**Comment by rndthoughts** [comment]
OK - setting either of those properties doesn't fix the problem.  It always affects the outgoing caller.  We have managed to run our application a couple of times in between without the echo occurring but after another call it returns.

We are setting the active audio devices using.  Is there anything else to be aware of?  Could it be something to do with the Windows Wave Mapper?

`UserAgent.MediaManager.SetSoundDevices(playbackId, captureId)`

**Comment by rndthoughts** [comment]
Narrowed it down further, it's always the first outgoing call that experiences echo.  If that call is hung up then subsequent calls do not experience the problem

**Comment by siniypin** [comment]
Hmm, that sounds fishy. Can you collect SIP trace as well as library logs? First thing I'd check would be SDP headers to see what are the clients negotiating upon.

**Comment by rndthoughts** [comment]
Could you point me at some documentation as to how to capture the trace?  Do you mean use the logging library in pjsip4net?

**Comment by siniypin** [comment]
Yes, you need to set the following props in config:
```
logMessages="true" logLevel="5" traceAndDebug="true"
```
and route your logs anywhere you like, e.g. [file with log4net](https://gist.github.com/siniypin/7860265)

**Comment by rndthoughts** [comment]
I've copied the configuration but when running I get - 

```
An error occurred creating the configuration section handler for common/logging: Unable to create type 'Common.Logging.Log4Net.Log4NetLoggerFactoryAdapter, Common.Logging.Log4Net'
```

**Comment by siniypin** [comment]
A tiny bit more info here: https://github.com/siniypin/pjsip4net#logging

**Comment by siniypin** [comment]
Make sure all necessary libraries are there, e.g. log4net.

**Comment by rndthoughts** [comment]
To get it to run, I had to reference `Common.Logging.Log4Net208` to match the log4net version I was running or it couldnt find the adapter.  It now runs and should be writing logs to `log.txt` - presumably in the `bin` folder, but nothing is output?

**Comment by rndthoughts** [comment]
Further info - this is only happening when i run the app i've built on two different machines making an internal call.  If i mute the sound devices on the callee's app then the caller can still hear their own voice played back to them.  So it must be happening on the caller's app.

**Comment by rndthoughts** [comment]
Found it!  I had miscoded what happens when the anwering party picks up and interconnected two slots together!

**Comment by siniypin** [comment]
Hey, glad you've nailed it! Lessons learned? Should pjsip4net raise an exception or at least log a warning when someone tries to interconnect the same port?

**Comment by rndthoughts** [comment]
I think it's just down to my misunderstanding of how pjsip works in regards to the conference slots.  A warning would be good but I never got the logging to work - I just couldnt seem to configure NLog properly and didnt get any text output.

What would be really useful is an example of answering a call in the testing console application as that's what's missing.

**Comment by siniypin** [comment]
> What would be really useful is an example of answering a call in the testing console application as that's what's missing.
  
That's a good idea, thanks!
