### ISSUE TITLE
How can makecall with custom sip headers?

### ISSUE THREAD

**Issue by modernstar** [siniypin/pjsip4net#112]
Hi
Is there any way to add custom headers with call the "makecall" method?

regards

**Comment by siniypin** [comment]
Hello,

unfortunately pjsip4net doesn't provide such features with its' high-level API as of the moment. However you can use a low level API wrapper that can be found in Interop library to manually dispatch pjsip calls with custom headers using P/Invoke wrapper functions.

Cheers
