### ISSUE TITLE
Play a wav in a call 

### ISSUE THREAD

**Issue by IvyMasterDiego** [siniypin/pjsip4net#113]
hello, this library has the method to reproduce or play a .wav during the call? 
and how i implement that? 
and receive a dtmf?

**Comment by siniypin** [comment]
https://gist.github.com/siniypin/47326a9fd78af95a3ff7

**Comment by siniypin** [comment]
https://github.com/siniypin/pjsip4net/blob/master/pjsip4net/Interfaces/ICallManager.cs#L17
