### ISSUE TITLE
Very unfriendly to the novice have a complete call demo can provide foreign friends need support

### ISSUE THREAD

**Issue by YC946586** [siniypin/pjsip4net#117]
**Describe the bug**

**To Reproduce**
1. '...'
2. '....'
3. '....'

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - A type of network between you and your callee/registrar server [e.g. NAT, firewall, etc]

**App configuration (please complete the following information):**
 - Either an  xml config: [e.g. App.config]
 - or a code config: [e.g. custom IConfigurationProvider, fluent config]

**Additional context**

**Comment by siniypin** [comment]
Kindly provide a description
