### ISSUE TITLE
WavPlayer

### ISSUE THREAD

**Issue by egondadalt** [siniypin/pjsip4net#16]
Hello. I have add the WavPlayer to the containter, using container.Register<IWavPlayer, WavPlayer>();

So, the pjsip4net.Interfaces.ISipUserAgent ua have this container. 

My question, who i can use the WavPlayer to send a sound to a call?

**Comment by siniypin** [comment]
Here is an example:
https://gist.github.com/siniypin/47326a9fd78af95a3ff7
