### ISSUE TITLE
Issue when use asterisk option reinvite

### ISSUE THREAD

**Issue by lcop200685** [siniypin/pjsip4net#17]
Hello

I have a problem with your library, when I push in my extension the option canreinvite= no, i can do a comunication fine, with other sip clients, using codecs g722, pcmu, gsm, but when i push the option canreinvite=yes,, the call connect, but the media is in silence in the sip clients,

I'm agree with your answer, because i need to connect rtp directly with the other clients.

**Comment by siniypin** [comment]
As I know nothing about your system configuration I can only speculate. To me this doesn't seem to be a problem with library, but with a network configuration most likely. It looks like in the first case media stream is relayed via Asterisk, and in the second - not. Can't help with this.
