### ISSUE TITLE
Detect when a wav-file has terminated playing

### ISSUE THREAD

**Issue by pietmortier** [siniypin/pjsip4net#19]
Is it possible to detect when a wav-files has terminated playing. 

pjmedia_wav_player_set_eof_cb => is it useable ? 

Thx

**Comment by siniypin** [comment]
`pjmedia_wav_player_set_eof_cb` is a part  of newer unsupported API. there is no callback in 1.4 version that is currently used by pjsip4net. However we can compare current sample with total samples number in file to find out if it was played to the end. 
I will add this feature shortly.

**Comment by pietmortier** [comment]
Hi Robert,

Thanks for the quick response.

I was trying whole day.

You make my day good.



2015-02-12 20:30 GMT+01:00 Robert <notifications@github.com>:

**Comment by siniypin** [comment]
WavPlayer now have an event to report the end of the file. A handler is triggered in non looped mode only. Use it like in the following example:
https://gist.github.com/siniypin/08aba26ffea06915136d

**Comment by siniypin** [comment]
Hi, it is documented in #15.
