### ISSUE TITLE
How to record Incoming Call?

### ISSUE THREAD

**Issue by lcop200685** [siniypin/pjsip4net#20]
Hi

In the last commit, I see you upgrade the code, adding record call function, but only when i make a call, but this option isn't available in Incoming Call process, 

Do you integrate this function coming soon ?

**Comment by siniypin** [comment]
Hi this feature is available with the commit you mentioned. In order to record your incoming call you have to call `StartRecording` on your call's MediaSession object, but be sure to wait till it's active. 
I will provide a gist file later.

**Comment by siniypin** [comment]
I have added a global setting called autoRecording, you can specify it in config file or set on your UaConfig manually. See: https://github.com/siniypin/pjsip4net/blob/master/Tests/Integration/pjsip4net.Console/App.config#L10
This setting tells a library that every outgoing and every incoming calls are to be recorded in wav files and be stored in current working directory.

**Comment by lcop200685** [comment]
Hi, Thanks for your answer, In a local test, I try to edit the code because when a call is incoming, I receive a ICall Interface, it doesn't have to access to media session object, then I change the ICall Interface, adding to it a recordTo(string path) function, in it, I validate the active status call, and if it is true, i call the function startrecording();  the result is the wav file is created but, it's damage, I will implement your last changes and write again with the results

Thanks

**Comment by siniypin** [comment]
Send me a pull request and reference this issue if you succeed, please.

**Comment by lcop200685** [comment]
Hi
I Test the change with incoming call, and It works, I created a recordTo() function in the interface ICall and implement it in the Internal Class Call,  I validate if the media state is active, only i am pending to use your helper guard to return a new exception when the media isn't active, I,m using Tortoise to download the code,  and I don't know how to send a pull request in it.

**Comment by siniypin** [comment]
Hi,
please upload the patch with files you've changed somewhere and post a link here, so I could merge that with master branch.

Cheers

**Comment by siniypin** [comment]
Hi @lcop200685, would you like to make your patch public or should I close this?

Cheers

**Comment by lcop200685** [comment]
HI @siniypin 

I like to make the patch public, in a few hour i will do this homework, I've been busy, i'm sorry

**Comment by lcop200685** [comment]
I've committed the code last week, if you have any doubt, please say me, or if you need any help with improves to the pjsip4net project  Thanks

**Comment by siniypin** [comment]
Sorry, where did you commit your code to? Can you provide a reference, please?

**Comment by lcop200685** [comment]
I'm a noob in a Git Repository, I'm sorry, the pull request is ready,
