### ISSUE TITLE
Question : can we access pjsua directly?

### ISSUE THREAD

**Issue by percramer** [siniypin/pjsip4net#21]
Hi,

so i got something working with swig and pjsua2 but it seems to be to limited. After some contact with the support of pjsip (Teluu) we tested the following :

The goal is to open a soundcard and have each output available as a mono port in the conference bridge. The tested code is 

1. Create splitcomb with 8 channels
2. Create reverse channel for each additional channel and add the port to the conference bridge.
3. Open the sound device with 8 channels.
====
    /* Create splitcomb with 8 channels */
    /* Create stereo-mono splitter/combiner */
    status = pjmedia_splitcomb_create(app_config.pool, 
PJMEDIA_PIA_SRATE(&conf->info) /* clock rate */,
8    /* 8 channels */,
2 * PJMEDIA_PIA_SPF(&conf->info),
PJMEDIA_PIA_BITS(&conf->info),
0    /* options */,
&app_config.sc);

    pj_assert(status == PJ_SUCCESS);

    /* Connect channel 0 to conference port slot0 */
    status = pjmedia_splitcomb_set_channel(app_config.sc, 0 /* ch0 */, 
  0 /*options*/,
  conf);

    /* Create reverse channel for channel1 ... */
    status = pjmedia_splitcomb_create_rev_channel(app_config.pool,
 app_config.sc,
 1  /* ch1 */,
 0  /* options */,
 &app_config.sc_ch1);
    pj_assert(status == PJ_SUCCESS);

    status = pjsua_conf_add_port(app_config.pool, app_config.sc_ch1, 
&app_config.sc_ch1_slot);
    pj_assert(status == PJ_SUCCESS);

    ..........
    ..........

    /* Create reverse channel for channel7 ... */
    status = pjmedia_splitcomb_create_rev_channel(app_config.pool,
  app_config.sc,
  7  /* ch7 */,
  0  /* options */,
  &app_config.sc_ch7);
    pj_assert(status == PJ_SUCCESS);

    status = pjsua_conf_add_port(app_config.pool, app_config.sc_ch7, 
 &app_config.sc_ch7_slot);
    pj_assert(status == PJ_SUCCESS);
    
    /* Create sound device */
    status = pjmedia_snd_port_create(app_config.pool, -1, -1, 
    PJMEDIA_PIA_SRATE(&conf->info),
     8    /* 8 channels */,
    2 * PJMEDIA_PIA_SPF(&conf->info),
    PJMEDIA_PIA_BITS(&conf->info),
    0, &app_config.snd);

    pj_assert(status == PJ_SUCCESS);

    /* Connect the splitter to the sound device */
    status = pjmedia_snd_port_connect(app_config.snd, app_config.sc);

But this is done directly in the C sample demo and there is no way to do this with pjsua2. So i was wondering if pjsip4net has got this kind of lower level access to pjsua?

Regards,

Per

**Comment by siniypin** [comment]
The short answer would be - no, pjsip4net does not provide low level API access. The pjsua.dll I've built exports high-level pjsua API functions.

The long answer is - it is certainly possible to add support for lower-level pjsip APIs by building a new .dll with more functions imported and generating new interop code. Although it is contrary to pjsip4net concept of a high level OOP interface to pjsua API. 

I currently have no plans to do this.

**Comment by siniypin** [comment]
However, if you are willing to take over this task and add these features to pjsip4net I will be happy to get a pull request.

**Comment by percramer** [comment]
Hi,

well i am of course willing to do this, but is your pjsua.dll source also in this project? Because i then might be overlooking it and need new glasses...

**Comment by siniypin** [comment]
pjsua.dll is provided as an external dependency. pjsip4net includes interop code library. So you have to do two simple things:

1. build your version of pjsua(_actually_whatever_you_name_it_).dll with desired functions exported;
2. generate a C# interop code that will make use of functions exported from your dll and add this code to a new Interop_(_whatever_you_name_it_) project in pjsip4net solution. You should also implement several interfaces to connect your interop code to pjsip4net core. Please see pjsip.Interop for example.

Waiting forward for your pull request.
Cheers.
