### ISSUE TITLE
It is possible to receive unregistered calls?

### ISSUE THREAD

**Issue by daplp** [siniypin/pjsip4net#22]
Hi,

I am using pjsip4net to call directly using a SPA3102 gateway, It works fine for outbound calls, but I want to receive calls using only the SPA3102 and pjsip4net, That it doesn't work because the library is unavailable to fixing one sip port to receive these unregistered calls.

Is there any way to receive unregistered incoming calls?.

Thanks.

**Comment by siniypin** [comment]
Hi,

is anything like this http://www.cisco.com/c/en/us/td/docs/voice_ip_comm/cucme/admin/configuration/guide/cmeadm/cmetrans.html#67223 possible with SPA3102? Did I get you with 'unregistered call' correctly?

Cheers

**Comment by daplp** [comment]
Hi,

Not, It isn't possible to doing that with SPA3102. 
Linksys SPA3102 have only a fixed web administration. If I want to use only SPA3102 to receiving calls, it needs to be set up a dial plan, where all incoming calls from PSTN go to a SIP device (with a fixed port)  and here is the problem due to that pjsip4net needs inevitably to be registered with SIP account. 
I have tried to receive calls in this mode using XLite which permits to use it without registration and It worked well, only I had to uncheck the option "Register with domain and receive incoming calls" and configure the fixed ports at topology tab.

Thanks!.

Regards.

**Comment by siniypin** [comment]
Hm, you can omit registering any accounts and you'll get a default local account that listens to any incoming SIP messages on udp/tcp port you've configured.

**Comment by daplp** [comment]
I didn't know that. Now if it is possible, Can you tell me how to configure that port to listen any incoming SIP messages?.

Thanks.

**Comment by siniypin** [comment]
You just define the SIP transport and specify a port (5060 is the default one) to listen to. Like in the following example: https://gist.github.com/siniypin/7860029

**Comment by daplp** [comment]
Thank you!. I'll try doing that.

Thank you very much by help.

Kind regards.

**Comment by siniypin** [comment]
You are welcome.

On Friday, 27 March 2015, daplp <notifications@github.com> wrote:

> Thank you!. I'll try doing that.
>
> Thank you very much by help.
>
> Kind regards.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/siniypin/pjsip4net/issues/22#issuecomment-87027907>.
>


-- 
Best regards,
Boris Tveritnev
de.linkedin.com/pub/boris-tveritnev/11/3a4/113/
www.xing.com/profile/Boris_Tveritnev

**Comment by siniypin** [comment]
I assume it is solved.
