### ISSUE TITLE
SipUriParser do not recognize domain name

### ISSUE THREAD

**Issue by SafinRR** [siniypin/pjsip4net#23]
Hello!!

var call = ua.CallManager.MakeCall (account, "sip:sip@bee.work.ru:5060") throw an  exception, but   var call = ua.CallManager.MakeCall(account, "sip:sip@192.168.9.49:5060"); works fine.

System.ArgumentOutOfRangeException was unhandled
  HResult=-2146233086
  Message=Argument out of range.
Имя параметра: index
  Source=mscorlib
  ParamName=index
  StackTrace:
       в System.ThrowHelper.ThrowArgumentOutOfRangeException()
       в System.Collections.Generic.List`1.get_Item(Int32 index)
       в pjsip4net.Core.Utils.NfaWithBackTracking`2.ConsumeInputSymbol(S symbol) в D:\srr\prj\vstudio\SIP\pjsip4net-master\pjsip4net\pjsip4net.Core\Utils\NfaWithBackTracking.cs:строка 42
       в pjsip4net.Core.Utils.NfaWithBackTracking`2.ComsumeAllInputSymbols(List`1 symbols) в D:\srr\prj\vstudio\SIP\pjsip4net-master\pjsip4net\pjsip4net.Core\Utils\NfaWithBackTracking.cs:строка 57
       в pjsip4net.Core.Utils.SipUriParser.ParseString(String sipUri) в D:\srr\prj\vstudio\SIP\pjsip4net-master\pjsip4net\pjsip4net.Core\Utils\SipUriParser.cs:строка 329
       в pjsip4net.Core.Utils.SipUriParser..ctor(String sipUri) в D:\srr\prj\vstudio\SIP\pjsip4net-master\pjsip4net\pjsip4net.Core\Utils\SipUriParser.cs:строка 288
       в pjsip4net.Calls.DefaultCallManager.<>c__DisplayClasse.<MakeCall>b__d(ICallBuilder x) в D:\srr\prj\vstudio\SIP\pjsip4net-master\pjsip4net\pjsip4net\Calls\DefaultCallManager.cs:строка 117
       в pjsip4net.Calls.DefaultCallManager.MakeCall(Func`2 builder) в D:\srr\prj\vstudio\SIP\pjsip4net-master\pjsip4net\pjsip4net\Calls\DefaultCallManager.cs:строка 126
       в pjsip4net.Calls.DefaultCallManager.MakeCall(IAccount account, String destinationUri) в D:\srr\prj\vstudio\SIP\pjsip4net-master\pjsip4net\pjsip4net\Calls\DefaultCallManager.cs:строка 115
       в pjsip4net.Console.Program.Main(String[] args) в D:\srr\prj\vstudio\SIP\pjsip4net-master\pjsip4net\Tests\Integration\pjsip4net.Console\Program.cs:строка 37
       в System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       в System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       в Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       в System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       в System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by siniypin** [comment]
Hi @SafinRR,

thanks for your error report, I'll take care of it.

Cheers

**Comment by SafinRR** [comment]
I have correction. I was write example with different domain name.
Symbol "-" crushes SipUriParser

            new SipUriParser("sip:sip@bee.work-it.ru:5060");
