### ISSUE TITLE
NuGet package for pjsip4net

### ISSUE THREAD

**Issue by siniypin** [siniypin/pjsip4net#24]
Several packages:
- core, 
- a mumber of interop packages per pjsip build supported.

**Comment by amccool** [comment]
I sent you a pull request with nuspec and nupkg files generated and appear to be working "well enough"

**Comment by siniypin** [comment]
Hi, thanks a lot! I'll merge it in a couple of days.

**Comment by amccool** [comment]
@siniypin hold off on that pull request.    I've never used uppercut before, and see there is a process for generating the nupkg file in the build
