### ISSUE TITLE
Recover audio call after remote hold

### ISSUE THREAD

**Issue by lcop200685** [siniypin/pjsip4net#26]
Hi Robert

I'm testing your library and i found a problem when the sip server have the reinvite option active, if I put hold in the remote device, the audio call is in silence, and arrive the MediaState.RemoteHold Event in the change status call, but when i remove the hold, the active event don't work and the audio never active again. 

I'm grateful with your opinion about the topic, i'm working to resolve it

**Comment by siniypin** [comment]
Hi @lcop200685,

can you show your config? Is there anything in logs that suggests the problem?

Cheers

**Comment by lcop200685** [comment]
Hi Robert 

I'm using my own class config , it only have this data
![image code config pjsip4net class](https://cloud.githubusercontent.com/assets/3520983/7394202/bd4bc5aa-ee57-11e4-83c0-7946ea7b3722.PNG)

I'm resolve the problem changing the original RemoteHoldMediaState 
![original](https://cloud.githubusercontent.com/assets/3520983/7394938/78556ba4-ee5c-11e4-9d51-4280c2082030.PNG)

to this, It is similar to LocalHoldMediaState
![changes in remote hold](https://cloud.githubusercontent.com/assets/3520983/7394978/a8921a7e-ee5c-11e4-9191-96ca8f88448b.PNG)

It wokrs but in this moment, i have a problem with the function call.ReleaseHold() when I put local hold, i'm working in that

**Comment by lcop200685** [comment]
Hi Robert

The fail of the function call.releaseHold(), is other topic, I'm going to put it in a new Issue, 

In this moment the change I've done in the class RemoteHoldMediaState works ok, if you like, i could send you a pull request, in a similar form i've repair other bug with the dispose to the recorder when the remote caller hangup the call

**Comment by lcop200685** [comment]
The case of the releaseHold function is a mistake mine, i'm sorry, the functions works ok

**Comment by siniypin** [comment]
I appreciate the work you did, please send your fix and I will merge it.

Cheers
