### ISSUE TITLE
Use Echo Cancelation 

### ISSUE THREAD

**Issue by lcop200685** [siniypin/pjsip4net#27]
Hi Robert

This isn't a issue, it's only a question, How can i use the function IMediaApiProvider,SetEc(int x, int options)

**Comment by siniypin** [comment]
Hi @lcop200685,

pjsip4net relays this call to pjsua media API function [pjsua_set_ec](http://www.pjsip.org/docs/latest-1/pjsip/docs/html/group__PJSUA__LIB__MEDIA.htm#gafa70df7a2298b8c80343ae69380c701c). You can pass EC tail length in ms and [options flags mask](http://www.pjsip.org/docs/latest-1/pjmedia/docs/html/group__PJMEDIA__Echo__Cancel.htm#gaa92df3d6726a21598e25bf5d4a23897e), that usually should be equal 0.

Cheers.
