### ISSUE TITLE
Record Wav file without call

### ISSUE THREAD

**Issue by lcop200685** [siniypin/pjsip4net#28]
Hi Robert 

This is a Question too,  Does pjsip4net have any api to record Audio Mic without calling process?

**Comment by siniypin** [comment]
Hi @Icop200685,

pjsip4net exposes pjsua conference bridge API as is, so basically anything you can do with it in C pjsip code is available to you as well. As for your question, you can find an answer here: [Recording mic to file](https://trac.pjsip.org/repos/wiki/audio-how-to-record) - point 6.

Cheers.
