### ISSUE TITLE
Call Leg persistence - CallId as a string

### ISSUE THREAD

**Issue by amccool** [siniypin/pjsip4net#31]
I would like to persistence the call leg information so that I can have another node pick processing the call dialog if the originating node failed.

I'd like to use the Call-ID from within the SIP message
From: sip:192.168.202.63;tag=52929a76489d4f5bad55ef973c9b8f7e
To: sip:billy@127.0.0.1
Contact: sip:192.168.202.63:5060
Call-ID: 9aff0d670e52410b86144e047584038a
CSeq: 16702 INVITE

How can I get this Call-ID?   The callId in the ICall object appears to be a simple int starting at 0

**Comment by amccool** [comment]
I see want I really want is the CallInfo class in pjsip4net.Core.Data.  However I cant see how to get it out of the ICall interface.   Is this intention?

**Comment by amccool** [comment]
looks like adding
CallInfo GetCallInfo();   to ICall
solves my data issue.

**Comment by siniypin** [comment]
Hi,

the idea was to keep the interface as decoupled from the downstream library as possible. Looking back I see no point in this anymore. I'd be happy to get this pull request from you.

Cheers.
