### ISSUE TITLE
Streaming audio to remote party

### ISSUE THREAD

**Issue by VincentGijsen** [siniypin/pjsip4net#37]
I cannot seem to stream audio to the remote party:

the sample:
``` 
public class PlayFileCommand : ICommand
    {
        private readonly ISipUserAgent _userAgent;
        private readonly IContainer _container;

        public PlayFileCommand(ISipUserAgent userAgent, IContainer container)
        {
            _userAgent = userAgent;
            _container = container;
        }

        public void Execute()
        {
            var player = _container.Get<IWavPlayer>();
            player.Completed += (sender, args) =>
            {
                System.Console.WriteLine("Player {0} has reached the end of file {1}", player.Id, player.File);
                player.Dispose();
            };
            player.Start("NeroSoundTrax_test8_PCM_Mono_VBR_16SS_48000Hz.wav", false) ;
            _userAgent.MediaManager.ConferenceBridge.ConnectToSoundDevice(player.ConferenceSlot.SlotId);
        }
    }
```

which i modified into:
```
       ua.MediaManager.Codecs.Each(x => _logger.Info("using codec" + x.CodecId));
            _logger.Info("Call is being created");

            call = ua.CallManager.MakeCall(x =>
                    x.To("1000")
                    .At("192.168.10.1")
                    .From(ua.AccountManager.GetAccountById(Convert.ToInt32(1)))
                    .Call());


            player = container.Get<IWavPlayer>();

            player.Completed += (senderAnon, args) =>
            {
                System.Console.WriteLine("Player {0} has reached the end of file {1}", player.Id, player.File);
                player.Dispose();
                ua.CallManager.GetCallById(call.Id).Hangup();
            };


            player.Start("Sound/windows-sound.wav", false);
            //ua.MediaManager.ConferenceBridge.Interconnect(player.ConferenceSlot.SlotId, call.ConferenceSlotId);

            ua.MediaManager.ConferenceBridge.ConnectToSoundDevice(player.ConferenceSlot.SlotId);
            ua.MediaManager.ConferenceBridge.ConnectCall(call);

          

            //  ua.MediaManager.ConferenceBridge.ConnectCall(call);
            Debug.WriteLine("cap: " + ua.MediaManager.CurrentCaptureDevice.Name);
            Debug.WriteLine("play: " + ua.MediaManager.CurrentPlaybackDevice.Name);
```

does play the audio locally, but I need it to play (at least) remotely, to the other party,

anyone got some pointers for this c#-sharp occasional programmer?

**Comment by siniypin** [comment]
Hi, I'm on vacation and will be able to dig into your case no sooner then
middle of August.

Cheers,
Boris Tveritnev

On Tuesday, 28 July 2015, Vincent Gijsen <notifications@github.com> wrote:

> I cannot seem to stream audio to the remote party:
>
> the sample:
>
> public class PlayFileCommand : ICommand
>     {
>         private readonly ISipUserAgent _userAgent;
>         private readonly IContainer _container;
>
>         public PlayFileCommand(ISipUserAgent userAgent, IContainer container)
>         {
>             _userAgent = userAgent;
>             _container = container;
>         }
>
>         public void Execute()
>         {
>             var player = _container.Get<IWavPlayer>();
>             player.Completed += (sender, args) =>
>             {
>                 System.Console.WriteLine("Player {0} has reached the end of file {1}", player.Id, player.File);
>                 player.Dispose();
>             };
>             player.Start("NeroSoundTrax_test8_PCM_Mono_VBR_16SS_48000Hz.wav", false) ;
>             _userAgent.MediaManager.ConferenceBridge.ConnectToSoundDevice(player.ConferenceSlot.SlotId);
>         }
>     }
>
> which i modified into:
>
>        ua.MediaManager.Codecs.Each(x => _logger.Info("using codec" + x.CodecId));
>             _logger.Info("Call is being created");
>
>             call = ua.CallManager.MakeCall(x =>
>                     x.To("1000")
>                     .At("192.168.10.1")
>                     .From(ua.AccountManager.GetAccountById(Convert.ToInt32(1)))
>                     .Call());
>
>
>             player = container.Get<IWavPlayer>();
>
>             player.Completed += (senderAnon, args) =>
>             {
>                 System.Console.WriteLine("Player {0} has reached the end of file {1}", player.Id, player.File);
>                 player.Dispose();
>                 ua.CallManager.GetCallById(call.Id).Hangup();
>             };
>
>
>             player.Start("Sound/windows-sound.wav", false);
>             //ua.MediaManager.ConferenceBridge.Interconnect(player.ConferenceSlot.SlotId, call.ConferenceSlotId);
>
>             ua.MediaManager.ConferenceBridge.ConnectToSoundDevice(player.ConferenceSlot.SlotId);
>             ua.MediaManager.ConferenceBridge.ConnectCall(call);
>
>
>
>             //  ua.MediaManager.ConferenceBridge.ConnectCall(call);
>             Debug.WriteLine("cap: " + ua.MediaManager.CurrentCaptureDevice.Name);
>             Debug.WriteLine("play: " + ua.MediaManager.CurrentPlaybackDevice.Name);
>
> does play the audio locally, but I need it to play (at least) remotely, to
> the other party,
>
> anyone got some pointers for this c#-sharp occasional programmer?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/siniypin/pjsip4net/issues/37>.
>


-- 
Best regards,
Boris Tveritnev
de.linkedin.com/pub/boris-tveritnev/11/3a4/113/
www.xing.com/profile/Boris_Tveritnev

**Comment by siniypin** [comment]
Hey Vincent, did you figure that out?

**Comment by VincentGijsen** [comment]
Well, no,

I couldn't figure out what the exact problem was. therefore I ended up using FreeSwitch as a softphone. Far from ideal.

So should you have some pointers on how to address this, please let me know!

**Comment by siniypin** [comment]
Hey Vincent,

in order to stream media to any recipient you have to connect them properly by calling `ConferenceBridge.Connect(sourceSlotId, receiverSlotId)`, where in your case slot id arguments identify player's sound port and a call's sound port, respectively. Connecting to sound device is not mandatory, unless you want to hear the sound stream yourself.
Although you did call `Interconnect` in the example provided a player object was a unidirectional media stream and could not accept input from other sources. That probably caused an internal error in pjsip. Did you try to call `Connect` with player and call slots?
Did you receive a sound on the other end from your local recipient call? Could it be a general sound problem related to your network setup?

**Comment by siniypin** [comment]
Sorry, just noticed that you did NOT connect your player's output to a call's input. Hence no sound.
So should you call `ConferenceBridge.Connect(player.ConferenceSlot.SlotId, call.ConferenceSlotId);` you should have heard a sound on the other end.
