### ISSUE TITLE
enabling ringback

### ISSUE THREAD

**Issue by marknelissen** [siniypin/pjsip4net#39]
Hi,

I've integrated pjsip4net in a WinForms C# .net solution. I can make outgoing calls, and have an event handler registered to handle incoming calls. When there is an incoming call, I see the log messages being generated, and can invoke the answer method on the ICall object. However, on the calling side, there is not tone to be heard, prior to answering the call (ringback tone). I fail to find any configuration option associated with this. How do you enable or specify the use of a ringback on incoming calls?

Similarly, what is the best way to trigger ringing on the client side? Do I do this in the incoming call event, or the ring event? And if in the ring event, how does this event behave or is used?

**Comment by siniypin** [comment]
Hey Mark,

there are no sounds or tone generators that pjsip4net readily provides (yet), although pjsip (an underlying SIP library) does have a tone generator implemented. Therefore, it is up to an application developer to playback sounds to your users utilizing tools that you are comfortable with. 
They can use pjsip4net implementation of WavPlayer (see this gist: https://gist.github.com/siniypin/47326a9fd78af95a3ff7 - yet they wouldn't have to connect a player to a call as in example provided). However WavPlayer has a restriction imposed by an underlying library implementation - only WAV files are supported (obviously), and the WAV file MUST be formatted as 16bit PCM mono/single channel (any clock rate is supported) http://www.pjsip.org/pjsip/docs/html/group__PJSUA__LIB__MEDIA.htm#ga90a2ec9c8516b5ad13b061a46ae1d07a. 
Alternatively, they can integrate any other sound library of their choice. NAudio (https://github.com/naudio/NAudio) is rather popular and easy to use one.

Anyway one'd still have to decide what sound and when to play. Therefore there is a `Ring` event provided by a `CallManager`. This event is raised with an argument of `RingEventArgs` type that provides two properties to aid in making these decisions. The first one is `RingOn`, a boolean property telling whether a call has to have a sound on or off. The second one is `IsRingback`, telling whether to play a ringback or a ring tone (One could also tell it by the state of a call, yet my philosophy is that an event object should provide enough data to be handled without reading other data sources). Please find an example of Ring event in the following gist: https://gist.github.com/siniypin/9c30a6d33c1734e77954

Hope that makes sense. 

P.S. I noticed a slight error in the code that raises a ring event that I have fixed. I will upload a new nuget package today.

Regards, Robert.

**Comment by siniypin** [comment]
UPD: a current nuget version is 0.2.0.28

**Comment by marknelissen** [comment]
Thank you for the information.

**Comment by Lanista12** [comment]
Hello, Siniypin.
I did as you said, but on incoming call c_userAgent.CallManager.Calls.First.ConferenceSlotId return -1. So, until I pick up the phone call, I can't send any audio.
What should I do?

**Comment by siniypin** [comment]
@Lanista12 please open a new issue if you have any specific problems.
