### ISSUE TITLE
Unable to make a call

### ISSUE THREAD

**Issue by hgencer** [siniypin/pjsip4net#44]
Hi,

First thank you for this project. I have a problem with making call. I successfully make a call your pjsip4net.Console.exe program with makecall command.

But I want to a bit change program. I changed code to this:

```
try
            {
                string number = "xxxx";//which is what I want to make a call number.
                string makeCall = "makecall -t:" + number + " -a:10.1.2.1 -f:1 -Through:5060";
                ICommand command = factory.Create(makeCall);
                command.Execute();
            }
            catch (PjsipErrorException e)
            {
                System.Console.WriteLine(e.Message);
            }
            catch (SystemException e)
            {
                System.Console.WriteLine(e.Message);
            }
```

debug informations writes in console but nothing to do. This line writes in console.
`pjsua_call.c  Timed-out trying to acquire dialog mutex (possibly system has deadlocked) in pjsua_call_get_info()`

 I tried to debug but I couldn't understand what is the problem.

I just make a call to number which read from args or file. But unfortunately did it.

After that, I try make own console application. Create new console project in x86 mode. Referenced neccesary dlls, copy native pjsip dlls. It runs but same exception throws.

`pjsua_call.c  Timed-out trying to acquire dialog mutex (possibly system has deadlocked) in pjsua_call_get_info()`

Maybe I can't see a basic problem. Bu I really understans what is the problem.

I send siptrace file in attachment for more information
[siptracegit.txt](https://github.com/siniypin/pjsip4net/files/175576/siptracegit.txt)

**Comment by hgencer** [comment]
I think I found the reason. In console programs, if main thread ends the program ends. I forget this. I added Thread.Sleep(-1) end of the Main method and problem has gone away :) It works expected now.

**Comment by siniypin** [comment]
Cool ;)
