### ISSUE TITLE
no sound on speaker&mic [question]

### ISSUE THREAD

**Issue by app1epie** [siniypin/pjsip4net#45]
I try was trying to make a "ring and auto-answer" softphone, everything was working fine (ring, auto-answer, end-call), except the sound. No sound coming out from the speaker or going through the mic. I wasn't sure it was my laptop sound device problem, because I tried all the drivers, and the application did appear in the "window sound mixer". Anyone faced this problem before? 
I am wondering what else did I missout... 

Here is my config was using the default config:
```
<sipua srtp="Disabled" secureSignaling="0" logMessages="false" logLevel="5" traceAndDebug="false" autoAnswer="true" autoRecording="false" autoConference="false" maxCalls="1">
    <accounts>
    </accounts>
    <sipTransport type="udp" Port="5080" />
    <networkSettings natInSDP="true" forceLooseRoute="false">
      <!--<stun address="stun.stunprotocol.org"/>-->
      <turn enabled="false" server="" type="udp" userName="" password="" realm="*" />
      <ice enabled="false" noRTCP="false" />
      <!--<proxies>
        <add address="sip:proxy.sipthor.net"/>
      </proxies>-->
    </networkSettings>
    <media isVADEnabled="true" playbackDeviceId="3" captureDeviceId="1" />
  </sipua>
```

**Comment by siniypin** [comment]
Hey, just a quick check: did you change your sound device ids?

**Comment by app1epie** [comment]
Yes I did change the "playbackdeviceid" and "capturedeviceid", I referred it from the capture devices and playback devices in the Media manager

**Comment by app1epie** [comment]
Hi siniypin, to test out the sound device, I made a "make a call" function from my app. The speaker and mic was working fine, me and destination url is able to hear each other. 
- when pbx ring my application with auto answer, no phone-tone sound heard in my speaker, could it be something to do with "conference" setting that I miss-out ?

**Comment by siniypin** [comment]
Hey @app1epie, provided that your app had the same setup (the same config and the same code basically) in both of these tests - point-to-point call and a call via PBX, than it was very likely to be a network problem between a callee and PBX. Here is a checklist to consider: https://trac.pjsip.org/repos/wiki/sound-problems

**Comment by app1epie** [comment]
Hi @siniypin, ok I'll try to test with your reference later :)
I didn't make a point-to-point call, I called through the PBX to destination
so far, I tested:
- MicroSIP (app) based on pjsip, works well (too many unwanted functions, and I had forgotten c++)
- Sipek Voip sdk also based on pjsip, it works, the ring from pbx able to have audio from/to destination (miracle, but the documentation (facepalm)) 

pjsip4net, I still unable to make it works... let me looks for solutions. I don't believe it cannot works... must be something missing. Thank you

**Comment by siniypin** [comment]
The auto answer feature simply calls the `Answer` method for you. That causes a call to be connected to capture and playback devices via a conference bridge eventually. Here: https://github.com/siniypin/pjsip4net/blob/master/pjsip4net/Calls/ActiveMediaState.cs#L20
Are BPX and a client in the same network? Try enabling ICE to let pjsip to find a way around NAT, should there be one. To enabled it you only need to change this line in your config:
```
<ice enabled="true" noRTCP="false" />
```
