### ISSUE TITLE
IM max length 

### ISSUE THREAD

**Issue by mandar003** [siniypin/pjsip4net#47]
Hi I am getting max length error while sending the Message/IM.

PJSIP_EMSGTOOLONG this is the error code how can I Increase the MaxLenght.
I tried to change  public const int PJSIP_MAX_PKT_LEN = Int32.MaxValue; but it did not work
Please help

**Comment by siniypin** [comment]
Hi, basically you have two options.
Either you build your custom version of pjsua.dll with the aforementioned constant set to higher value (not sure if that is possible at all), or you break longer messages into chunks and glue them together back on the application level.

**Comment by siniypin** [comment]
Following this discussion https://www.ietf.org/mail-archive/web/sip/current/msg02446.html one possible solution might be to use TCP transport instead of UDP. Can you give it a try?

**Comment by siniypin** [comment]
Closing as answered.
