### ISSUE TITLE
will pjsip4net work with the new pjsip 2.5?

### ISSUE THREAD

**Issue by aleh4d** [siniypin/pjsip4net#48]
will pjsip4net work with the new pjsip 2.5?

**Comment by siniypin** [comment]
Hi, unfortunately I have no time for pjsip 2.x line support. Although there were some discussions here and I even got a Swig (http://www.swig.org/) project to generate bindings to the native code contributed, but no one was ever able to go any further.  
I you feel like you can do it, I can share those Swig files with you as well as try to help you with advice.

**Comment by amccool** [comment]
do you still have the swig files?

**Comment by siniypin** [comment]
I've got swig generated bindings and a readymade dll built for pjsip v. 2.4.5.  
However, I think it should be easy to create your own up to date version, following the steps described here https://github.com/StrikeForceZero/PJSip-CSharp/blob/master/README.txt

**Comment by siniypin** [comment]
@amccool Do you need these bindings anyway?
