### ISSUE TITLE
RegisterTransport - both tcp and udp

### ISSUE THREAD

**Issue by amccool** [siniypin/pjsip4net#49]
Is it possible to register both a udp transport AND a tcptransport on the same instance?

if I register a TCP transport AFTER and udp transport I get:
```
An exception of type 'pjsip4net.Core.PjsipErrorException' occurred in pjsip4net.Core.dll but was not handled in user code

Additional information: PJSIP error code =  16:54:40.596   pjsua_core.c  Error creating SIP TCP listener: Invalid value or argument (PJ_EINVAL) [status=70004]

 in CreateTransportAndGetId
```

using

```
                var udpTransportType = new pjsip4net.Core.Data.TransportConfig()
                {
                    BoundAddress = "0.0.0.0",
                    Port = (uint)udpPort,
                    PublicAddress = "0.0.0.0",
                };

                var udp = new pjsip4net.Core.Utils.Tuple<pjsip4net.Core.TransportType, pjsip4net.Core.Data.TransportConfig>
                        (pjsip4net.Core.TransportType.Udp, udpTransportType);
                o.RegisterTransport(udp);
```

However if I register the UDP transport after the TCP, things seem to work (using UDP it appears)

**Comment by siniypin** [comment]
Hey Alex, this thread suggests there may be a problem with a port number: http://lists.pjsip.org/pipermail/pjsip_lists.pjsip.org/2010-April/010793.html
Could you give it a try with another port?

**Comment by amccool** [comment]
Using

```
            cfg = cfg.WithSipTransport(o =>
            {
                return new pjsip4net.Core.Utils.Tuple<pjsip4net.Core.TransportType, pjsip4net.Core.Data.TransportConfig>
                (pjsip4net.Core.TransportType.Udp, new pjsip4net.Core.Data.TransportConfig() { });
            });
```
and/or
```
            cfg = cfg.WithSipTransport(o=>
            {
                return new pjsip4net.Core.Utils.Tuple<pjsip4net.Core.TransportType, pjsip4net.Core.Data.TransportConfig>(pjsip4net.Core.TransportType.Tcp, new pjsip4net.Core.Data.TransportConfig()                {  });
            });
```

before calling cfg.Build();

What I see is that using the defaults of the `TransportConfig` is giving me a random port.   That's perfect.
However If I try to use both WithSipTransports (one for udp and one for tcp), only the last one is used.   I supposed that is fine.   If this is expected behavior lets close this (perhaps document it).

In reality what I really want is something that tries the transports in order (if there are multiple transports is there a priority?).   E.g.  try using secure TCP, if that fails, try secure UDP, if that fails, try TCP, if that fails try UDP, if that fails go nuclear.

**Comment by siniypin** [comment]
Well, pjsip itself allows spinning multiple transports of different types (not sure if you can register several of the same kind though). So it should be possible with pjsip4net as well, although I never tested this scenario as the focus was to provide just one user agent but fully setup for work.  
Nevertheless, pjsip can not transparently enumerate transports to pick the right one as long as transport is a part of URI, a scheme (sip/sips) and a transport type param. Whenever you try to connect anywhere you should already make a decision of which transport to use upfront and specify it with URI. So I'd say this is a higher level logic of your app to make sure you have all the endpoints necessary to try different connection options.  
As for the multiple transports I think it should work, I've marked this issue as a bug. Unfortunately, I won't have time to fix it in near future. So pull requests are welcome!

**Comment by siniypin** [comment]
OK, so I'll document the transport 'feature'. Thanks for the question.
