### ISSUE TITLE
Value ca not be null in build().Start()

### ISSUE THREAD

**Issue by jackesdavid** [siniypin/pjsip4net#51]
I dont know why i am getting this error...
weeks of searching...

please help-me!

![image](https://cloud.githubusercontent.com/assets/5096584/18753968/02f1f778-80b5-11e6-8599-6d69f569870d.png)

   em System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   em System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   em System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   em System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   em System.Activator.CreateInstance(Type type, Object[] args)
   em pjsip4net.Core.Container.SimpleContainer.RegisterAsSingleton[T,T1]() na c:\work\pjsip4net\pjsip4net.Core\Container\SimpleContainer.cs:linha 49
   em pjsip4net.Core.Container.SimpleContainer.RegisterAsSingleton[T,T1,T2]() na c:\work\pjsip4net\pjsip4net.Core\Container\SimpleContainer.cs:linha 57
   em pjsip4net.Configuration.DefaultComponentConfigurator.Configure(IContainer container) na c:\work\pjsip4net\pjsip4net\Configuration\DefaultComponentConfigurator.cs:linha 20
   em pjsip4net.Core.Configuration.Configure.<RunConfigurators>b__2(IConfigureComponents c) na c:\work\pjsip4net\pjsip4net.Core\Configuration\Configure.cs:linha 121
   em pjsip4net.Core.Utils.Extensions.Each[T](IEnumerable`1 collection, Action`1 act) na c:\work\pjsip4net\pjsip4net.Core\Utils\Extensions.cs:linha 13
   em pjsip4net.Core.Configuration.Configure.RunConfigurators() na c:\work\pjsip4net\pjsip4net.Core\Configuration\Configure.cs:linha 121
   em pjsip4net.Configuration.BuildUserAgent.Build(Configure cfg) na c:\work\pjsip4net\pjsip4net\Configuration\BuildUserAgent.cs:linha 38
   em BIA.Core.Services.Voip.VoipService.Initialize() na E:\BIA\BIA.Core\Services\Voip\VoipService.cs:linha 42
   em BiaClient.App.<ConfigureServices>d__1.MoveNext() na E:\BIA\Bia.Client\App.xaml.cs:linha 46

Sample Code
``` 
            var transport = new System.Func<TransportType, TransportConfig>((t) => new TransportConfig() { Port = 5060 });

            var cfg = Configure
                .Pjsip4Net()
                .With(provider =>
                {
                    provider.Config.AutoAnswer = true;
                    provider.Config.AutoConference = false;
                    provider.Config.NatInSdp = true;
                })
                .WithSipTransport(o =>
                {
                    return new pjsip4net.Core.Utils.Tuple<pjsip4net.Core.TransportType, pjsip4net.Core.Data.TransportConfig>
                    (pjsip4net.Core.TransportType.Udp, new pjsip4net.Core.Data.TransportConfig() { });
                });

            UserAgent = cfg.Build().Start();
```

**Comment by siniypin** [comment]
Hey,

first of all, if you want to configure your transport with a code configuration, you could do it all in `Configure.With(IConfigurationContext)` method (line 5 in your example). Secondly, it is weird that you first define and then never use a factory function to create a transport config by defined type. And last and the most important, you don't need neither of that to get your user agent started with UDP transport with default settings, as long as user agent will create it all for you. UDP on port 5060 is a default SIP transport, no extra config needed. 

Let me know if you need any more help.

Cheers.

**Comment by siniypin** [comment]
@jackesdavid Any updates? Did you manage to run it?
