### ISSUE TITLE
disconnect call

### ISSUE THREAD

**Issue by khosrokhan** [siniypin/pjsip4net#54]
Hi all...
I am developing a softphone by pjsip4net project  .
When a softphone wants to disconnect call the call is disconnected successfuly but
when agent wants to disconnect call this the softphone does not recognize it .
please help me ...

**Comment by siniypin** [comment]
Can you please more information about your setup. What kind of network, what kind of server software, what is a softphone and an agent, etc etc etc? The more info you provide the easier it is to help you. Ideally I'd need a SIP trace to see what goes on in detail. 

You may want to checkout this hack https://gist.github.com/siniypin/a20f0cf37bfb7cbc24b9 we found to gracefully teardown a TCP session whenever a remote party silently closes a socket, if you use TCP as a session transport, of course.

**Comment by siniypin** [comment]
Any updates here? Can I close it?
