### ISSUE TITLE
create a softphone in Xbap project

### ISSUE THREAD

**Issue by khosrokhan** [siniypin/pjsip4net#55]
Hi
I wnat to create a softphone with pjsip open source project in Xbap (Xaml browser application) but 
it give me an error .
this error is  :
No component for supporting the service pjsip4net.Core.Interfaces.ApiProviders.IBasicApiProvider was found

**Comment by siniypin** [comment]
First of all, you need to make sure that pjsip.Interop.dll and pjsua.dll libraries are on the target machine and discoverable by your XBAP. Whereas the first lib is easy, you can simply reference and compile pjsip.Interop.dll into the binary, but pjsua.dll is a native Windows dll a can not be simply compiled into the XBAP. It is a x86 lib and can not be loaded by a x64 process. Honestly, I doubt it is even possible to run pjsip4net app from an XBAP, at least I never tested or targeted that environment. 
Anyway, give it a try, considering the notes above, and let me know if that works, eventually.

**Comment by siniypin** [comment]
So far so good? Anything you discovered and wanted to share with others?
