### ISSUE TITLE
Dnd in softphone pjsip4net

### ISSUE THREAD

**Issue by khosrokhan** [siniypin/pjsip4net#58]
Hi
How can I run DND mode in pjsip4net ?

**Comment by siniypin** [comment]
Hi, you can set any account status info using https://github.com/siniypin/pjsip4net/blob/master/pjsip4net/Accounts/Account.cs#L223

However, any special behaviour, depending on the meaning of the statuses of your accounts, like no ringtones, no messages advertised, you'd have to add on the application level. DND mode is not implemented as user agent behaviour.
I think it is worth adding as a built-in operation mode, and therefore I encourage you to provide a pull-request.

Cheers.
