### ISSUE TITLE
send sip message by pjsip4net 

### ISSUE THREAD

**Issue by khosrokhan** [siniypin/pjsip4net#60]
Hi
I want send sip message by pjsip4net . Hoiw can I do it ?

**Comment by siniypin** [comment]
Hi, anything you can do with pjsip4net is demonstrated in this small console app that comes along with the source code: https://github.com/siniypin/pjsip4net/tree/master/Tests/Integration/pjsip4net.Console

An answer to your particular question is here: https://github.com/siniypin/pjsip4net/blob/master/Tests/Integration/pjsip4net.Console/CommandFactory.cs#L108

Cheers
