### ISSUE TITLE
Caller does not rings

### ISSUE THREAD

**Issue by AverkinSergei** [siniypin/pjsip4net#62]
I have a working application based on library pjsip4net. But, unfortunately, when you call from a telephone on my application the caller does not rings. What can you recommend?

**Comment by siniypin** [comment]
Hi, please define 'does not ring'. pjsip4net comes with a couple of default sound files in the following folder https://github.com/siniypin/pjsip4net/tree/master/pjsip4net/Sounds. However, it doesn't play any of them by default, giving a developer a chance to provide their own files and connect to events of interest. An incoming call is accompanied by a Ring event https://github.com/siniypin/pjsip4net/blob/master/pjsip4net/Interfaces/ICallManager.cs#L18 telling app developer whether it has to playback a ring tone or mute it. 

Subscribing to event: https://gist.github.com/siniypin/9c30a6d33c1734e77954
Playing a sound: https://gist.github.com/siniypin/08aba26ffea06915136d

**Comment by AverkinSergei** [comment]
Caller is ip-telephone. I can not handle any events on ip-telephone. When you are calling from ip-telephone on my application and waiting for an answer, you do not hear any beeps in the handset.
How can I generate some sounds on remote ip-telephone?

**Comment by siniypin** [comment]
Let me double check - do you want to generate sound on a caller? Is caller a pjsip4net based app?

**Comment by siniypin** [comment]
Oh I got it. Pjsip doesn't reply with provisional responses, as long as not sending them is the default setting http://www.pjsip.org/docs/latest-1/pjsip/docs/html/structpjsua__config.htm#a41d0fcd0a69f2996a6803a17e4cdf8b6
To enable the ringback tone on your devices set a corresponding config property Require100Rel to true.

**Comment by AverkinSergei** [comment]
Thanks a lot!
