### ISSUE TITLE
Running into an error when running pjsip4net.Console

### ISSUE THREAD

**Issue by toLucky81** [siniypin/pjsip4net#64]
There is more issues.

I ran the Tests\Integration\pjsip4net.Console project and when it finally showed something on the console, it ran into this "

![image](https://cloud.githubusercontent.com/assets/23236098/19965453/50ff0bda-a1c7-11e6-9be7-349c110abc4a.png)

Any clues?

**Comment by siniypin** [comment]
Hey, sorry missed this one.

We've just found out that if you set a BoundAddress you'd also have to set a PublicAddress. That'd make an error mysteriously disappear. #65
