### ISSUE TITLE
Transfer inactive call

### ISSUE THREAD

**Issue by siniypin** [siniypin/pjsip4net#66]
Other question (sorry hijacking my own post) I'm trying to transfer a call before answering it (call forward) but the MediaState is not active, if I make it active the transfer works just fine...

However in all unit tests for transfer there is an explicit setup that the MediaState should be active, but how should i achieve this?

**Comment by siniypin** [comment]
@PaulSch  hi

**Comment by PaulSch** [comment]
Hi siniypin,
thanks for creating this new issue. I agree that it is a separate topic, and should be in a new thread.

Under certain situations I want to forward incoming calls from certain addresses to another address without answering them myself.
I thought that was what Transfer was for.

However the MediaState is inactive (and in the unit tests it is always set to active) and as far I could quickly find the MediaState would only become active if a call was answered? (or did I miss something)

**Comment by siniypin** [comment]
Hey, you are right there shouldn't be any problem transferring a not yet answered call. Can you kindly remove this check it to ignore the media state https://github.com/siniypin/pjsip4net/blob/master/pjsip4net/Calls/Call.cs#L280 and send me a pull request?

**Comment by PaulSch** [comment]
Yes I allready did that on friday, and it works just fine :)

**Comment by PaulSch** [comment]
Just tried to create a pull request, but I'm new to github and am missing something.... (also still waiting for the coffee machine to finish it's cleaning session ;-)

**Comment by siniypin** [comment]
ping =)

**Comment by PaulSch** [comment]
Again, I'm new to github, I did a checkout and made changes, I can commit those locally, can't push (and that is good ; - )
But still I have no options if I go to the pull requests tab...???

I changed call.cs:
`        public void Transfer(string destinationUri)
        {
            GuardDisposed();
            Helper.GuardNotNullStr(destinationUri);
            Helper.GuardIsTrue(new SipUriParser(destinationUri).IsValid);
            if (_mediaSession.IsActive || this._mediaSession.MediaState == CallMediaState.None)
                _callManager.CallApiProvider.TransferCall(Id, destinationUri);
        }`
And the unit test given_a_call:
`        [Test, Sequential]
        public void when_transfer_it_should_depend_on_media_state__should_delegate_call_to_provider([
                Values(
                    CallMediaState.None,
                    CallMediaState.Active,
                    CallMediaState.Disconnected,
                    CallMediaState.Error,
                    CallMediaState.LocalHold,
                    CallMediaState.RemoteHold)] CallMediaState mediaState, [Values(
                                                                                true,
                                                                                true,
                                                                                false,
                                                                                false,
                                                                                false,
                                                                                false
                                                                            )] bool shouldDelegate)
        {
            _provider.Setup(x => x.GetInfo(It.IsAny<int>()))
                .Returns(new CallInfo() {MediaStatus = mediaState});

            //arrange
            _sut.SetId(_fixture.CreateAnonymous<int>());
            _sut.HandleMediaStateChanged();

            //act
            _sut.Transfer("sip:sip@sip");

            //assert

            if (shouldDelegate)
            {
                _provider.Verify(x => x.TransferCall(It.Is<int>(x1 => x1 == _sut.Id), It.Is<string>(x1 => x1 == "sip:sip@sip")), Times.Once());
            }
            else
            {
                _provider.Verify(x => x.TransferCall(It.Is<int>(x1 => x1 == _sut.Id), It.Is<string>(x1 => x1 == "sip:sip@sip")), Times.Never());
            }
        }`

However I think the MediaSession is not reflecting the media states i'm testing, cause three fail. I had a quick look, but could not find it....

**Comment by PaulSch** [comment]
Okay figured out why I couldn't create the pull request :) duh I needed to create a fork first LOL
So now I have, and have submitted my request for you to review.
