### ISSUE TITLE
Can call, but not receiving anything

### ISSUE THREAD

**Issue by PaulSch** [siniypin/pjsip4net#67]
Hi Robert

I started moving your library into my project, and I think I copied the configuration over correctly using the fluent interface :) nice!
I can now make a call with the user agent, but if from my other client I use the connection history to call back there is no incoming call or state change occurring. Also if I initiate a call using the data supplied in the account info (which shows up in the other client) or if I use a direct ip address then there is no incoming call to observe.

Any suggestions as to what I am missing?

Regards,
Paul

**Comment by PaulSch** [comment]
addendum

This works:
userAgent.CallManager.MakeCall(x => x.To("XXX").At("172.16.2.145").Through("5060").From(userAgent.AccountManager.Accounts.First()).Call());

But this just hangs:
userAgent.CallManager.MakeCall(x => x.To("XXX").At("sip.linphone.org").Through("5060").From(userAgent.AccountManager.Accounts.First()).Call());

**Comment by PaulSch** [comment]
Furthermore, transfering a call also does not work anymore since I moved this stuff into my own project.
There is no ring activity?
Any suggestions would be welcome

**Comment by siniypin** [comment]
Hi Paul, 

unfortunately there isn't much I can help you with as long as interconnectivity with SIP is kind of tricky, unless you are in a strictly isolated network with no NATs and firewalls between.

You can switch the highest logging level on to collect the SIP traces to figure what is going on there under the hood. Please find an example here: https://gist.github.com/siniypin/7860029#file-app-config-L6

**Comment by PaulSch** [comment]
found in: `void pj_log_set_level(int level)`
level	The maximum level of verbosity of the logging messages (6=very detailed..1=error only, 0=disabled)

**Comment by PaulSch** [comment]
Finally got some where....
I was writing up my findings because I was getting nowhere... and as usual if you start to explain you notice the problem...

In the console app.config node
`    <sipTransport type="udp" Port="5080" BoundAddress="" PublicAddress=""/>`
it states port 5080, usually SIP uses 5060...so i thought it was for something else and paid no attention to it.

In the console test application log, I noticed it said:
`Account <sip:172.16.2.101:**5060**> added with id 0`

And in my application log it said:
`Account <sip:172.16.2.101:**5080**> added with id 0`

so when i changed my fluent config to port 5060, i started getting a connection...
it is still not fully working, but I wanted to report this, as there is a difference between the way the app.config and the fluent config are processed!

**Comment by PaulSch** [comment]
Same goes for the AutoAnswer property I think, because in the test console app this was set to true, and in my fluent configured app also, and i noticed that it was answering the call, so when I set that to false. I managed to transfer the call correctly!

You can close this thread, but I wanted to reply in case anyone else had configuration issues.

**Comment by PaulSch** [comment]
Also now it is obvious that I could call call from port 5080 to port 5060, but was not receiving on port 5080, as I was sending it to port 5060, and there was nothing listening at that port.

**Comment by siniypin** [comment]
Hey Paul,
> a difference between the way the app.config and the fluent config are processed!
what did you mean? Did you mean that one overrides the other?

**Comment by PaulSch** [comment]
I left the Port in the app.config file set to 5080, and did the same in the fluent config. But the console app worked, and my fluent app did not. until I changed the Port to 5060.

And from the log in the console app I could see it was using port 5060, even though the config was set to 5080.

I haven't looked into where it goes wrong, now that I'm configuring it correctly it works.

**Comment by PaulSch** [comment]
Very strange, this morning it did not work...
Set it back to 5080 and it worked again???
