### ISSUE TITLE
Make call to device on PSTN

### ISSUE THREAD

**Issue by Phrohdoh** [siniypin/pjsip4net#69]
How would this be done?

I cannot use the `MakeCall` command with `+1<tel-number>` because the `+` throws off the command parsing so this leads me to believe I am headed down the wrong trail entirely.

**Comment by siniypin** [comment]
You'd need a PSTN gateway: http://meetings.ripe.net/ripe-46/presentations/ripe46-eof-enum-sip-pstn.pdf

**Comment by Phrohdoh** [comment]
The issue I'm having (being completely new to the telephony world) is that I have no idea what domain should be used for what number.

So my plan is to use Asterisk as the gateway.
> Asterisk can be used to build a gateway using a standard computer and one or more telephony interface cards.

If I can get that working would I be able to use pjsip4net as the "softphone" or would I no longer need to use this project?

Thanks for your help so far! :-)

**Comment by siniypin** [comment]
The domain in the simplest case could be your Asterisk's IP address, although it depends very much on your setup, and yes, you can use pjsip4net to build a softphone calling to PSTN via a proxy for sure.
