### ISSUE TITLE
Sound problem

### ISSUE THREAD

**Issue by ftagliento** [siniypin/pjsip4net#72]
Hello,
I am trying to use pjsip4net in windowsform application. I am able to register, make call or receive.
Seems the connection data between parties is ok but no audio is available.
1. The ring is not played on receiver
2. After answer the audio is not working

Probably is configuration problem, I spent some hours to understand the problem and try to change configuration without success.
There is a check list I can verify the problem ? Or some suggestion ?

Could you help?
Thanks
Francesco

**Comment by siniypin** [comment]
Hi, 
this is by far the most popular question. The sound/connectivity problem is usually caused by a configuration that does not consider the environment (there are many things to check, like NAT, firewall, etc). Please consider these pages for a list of tips:  
https://trac.pjsip.org/repos/wiki/FAQ  
https://trac.pjsip.org/repos/wiki/sound-problems

**Comment by ftagliento** [comment]
Thanks Robert.
Actually I am testing with server linux Ubuntu 16 + Asterisk 13 on a VM Virtualbox on my laptop and using another laptop connected on the same network. 
If I use 2 client pjsip (pjsua) everithing works fine, so seems network configuration seems ok.
Also using 2 client locally with pjsua works fine instead with pjsip4net audio doesnt works.

Francesco

**Comment by siniypin** [comment]
@ftagliento 
1. pjsip4net does not stream the ringtone to the output stream automatically. You have to take extra steps to make your app ring. You can find an example of subscribing to the ring event here: https://gist.github.com/siniypin/9c30a6d33c1734e77954, - and playing a soundfile (a ringtone for instance) here: https://gist.github.com/siniypin/47326a9fd78af95a3ff7
2. Did you configure a speaker device? https://trac.pjsip.org/repos/wiki/audio-problem-local-no-audio

**Comment by ftagliento** [comment]
Hello Roberts.
OK for the ring, your suggestion solved the issue.
About the audio the problem is still there (of course is a big problem). I verified the devices and seems ok, also because using pjsip console its works fine. It doesnot work if I use pjsip4net, also pjsi4net.console has same issue. So probably I am missing something in the code, maybe I am not using right procedure to answer call or my configuration file is wrong.

Thanks
Francesco

**Comment by siniypin** [comment]
Can you kindly post your config file and parts of the code you configure the lib and a call with?

**Comment by ftagliento** [comment]
Hello Robert.
Here the co<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="sipua" type="pjsip4net.Configuration.SipUserAgentSettingsSection, pjsip4net, Culture=neutral, PublicKeyToken=null" />
    <sectionGroup name="common">
      <section name="logging" type="Common.Logging.ConfigurationSectionHandler, Common.Logging" />
    </sectionGroup>
    <section name="log4net" type="log4net.Config.Log4NetConfigurationSectionHandler, log4net, Version=1.2.10.0, Culture=neutral, PublicKeyToken=1b44e1d426115821" />
  </configSections>
  <sipua srtp="Disabled" secureSignaling="0" logMessages="true" logLevel="5" traceAndDebug="false" autoAnswer="false" autoRecording="true" autoConference="false" maxCalls="5">
    <accounts>
      
    </accounts>
    <sipTransport type="tcp" Port="5080">
    
    </sipTransport>
    <networkSettings natInSDP="false" forceLooseRoute="false">
      
      <turn enabled="false" server="" type="tcp" userName="" password="" realm="" />
      <ice enabled="false" noRTCP="false" />
      
    </networkSettings>
    <media isVADEnabled="false" playbackDeviceId="7" captureDeviceId="5" />
  </sipua>
  <common>
    <logging>
      <factoryAdapter type="Common.Logging.Log4Net.Log4NetLoggerFactoryAdapter, Common.Logging.Log4Net1210">
        <arg key="configType" value="EXTERNAL" />
      </factoryAdapter>
    </logging>
  </common>
  <log4net>
    <appender name="ColoredConsoleAppender" type="log4net.Appender.ColoredConsoleAppender">
      <mapping>
        <level value="ERROR" />
        <foreColor value="White" />
        <backColor value="Red, HighIntensity" />
      </mapping>
      <mapping>
        <level value="INFO" />
        <backColor value="Green" />
      </mapping>
      <mapping>
        <level value="WARN" />
        <backColor value="Yellow" />
      </mapping>
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%date [%thread] %-5level - %message%newline" />
      </layout>
    </appender>
    <appender name="FileAppender" type="log4net.Appender.FileAppender">
      <file value="siptrace.txt" />
      <appendToFile value="true" />
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%date [%thread] %-5level - %message%newline" />
      </layout>
    </appender>

    <root>
      <level value="DEBUG" />
      <appender-ref ref="ColoredConsoleAppender" />
      <appender-ref ref="FileAppender" />
    </root>
  </log4net>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0" />
  </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Core" publicKeyToken="b77a5c561934e089" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Common.Logging" publicKeyToken="af08829b84f0328e" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.1.0.0" newVersion="3.1.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
nfig file.

This is the code I use to config the lib.
            XmlConfigurator.Configure();
            _logger = LogManager.GetLogger("root");
            WindsorContainer container = new WindsorContainer();
            Configure cfg = Configure.Pjsip4Net().With_CastleContainer(container).FromConfig();
            _ua = cfg.Build().Start();

           _ua.CallManager.IncomingCall += CallManager_IncomingCall;
            _ua.CallManager.Ring += CallManager_Ring;
            _ua.CallManager.CallStateChanged += CallManager_CallStateChanged;
            _ua.AccountManager.AccountStateChanged += AccountManager_AccountStateChanged;

This is the code to register account
             var command1 = new RegisterAccountCommand(_ua, new RegisterAccountArguments
              {
                  Domain = "192.168.1.98",
                  Extension = "1003",
                  Password = "1003",
                  Port = "5060",
                  Transport = "tcp"
              });
              command1.Execute();

This is the code when I receive call.
   _ua.CallManager.Calls[0].Answer(true);
Before answer I tried also to use _ua.MediaManager.SetSoundDevices() using different devices configured. But no result.

Thanks
Best Regards
Francesco

**Comment by ftagliento** [comment]
Sorry I paste again config file. Seems not readble in the previous post
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="sipua" type="pjsip4net.Configuration.SipUserAgentSettingsSection, pjsip4net, Culture=neutral, PublicKeyToken=null" />
    <sectionGroup name="common">
      <section name="logging" type="Common.Logging.ConfigurationSectionHandler, Common.Logging" />
    </sectionGroup>
    <section name="log4net" type="log4net.Config.Log4NetConfigurationSectionHandler, log4net, Version=1.2.10.0, Culture=neutral, PublicKeyToken=1b44e1d426115821" />
  </configSections>
  <sipua srtp="Disabled" secureSignaling="0" logMessages="true" logLevel="5" traceAndDebug="false" autoAnswer="false" autoRecording="true" autoConference="false" maxCalls="5">
    <accounts>
      
    </accounts>
    <sipTransport type="tcp" Port="5080">
    
      
    </sipTransport>
    <networkSettings natInSDP="false" forceLooseRoute="false">
      
      <turn enabled="false" server="" type="tcp" userName="" password="" realm="" />
      <ice enabled="false" noRTCP="false" />
      
    </networkSettings>
    <media isVADEnabled="false" playbackDeviceId="7" captureDeviceId="5" />
  </sipua>
  <common>
    <logging>
      <factoryAdapter type="Common.Logging.Log4Net.Log4NetLoggerFactoryAdapter, Common.Logging.Log4Net1210">
        <arg key="configType" value="EXTERNAL" />
      </factoryAdapter>
    </logging>
  </common>
  <log4net>
    <appender name="ColoredConsoleAppender" type="log4net.Appender.ColoredConsoleAppender">
      <mapping>
        <level value="ERROR" />
        <foreColor value="White" />
        <backColor value="Red, HighIntensity" />
      </mapping>
      <mapping>
        <level value="INFO" />
        <backColor value="Green" />
      </mapping>
      <mapping>
        <level value="WARN" />
        <backColor value="Yellow" />
      </mapping>
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%date [%thread] %-5level - %message%newline" />
      </layout>
    </appender>
    <appender name="FileAppender" type="log4net.Appender.FileAppender">
      <file value="siptrace.txt" />
      <appendToFile value="true" />
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%date [%thread] %-5level - %message%newline" />
      </layout>
    </appender>

    <root>
      <level value="DEBUG" />
      <appender-ref ref="ColoredConsoleAppender" />
      <appender-ref ref="FileAppender" />
    </root>
  </log4net>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0" />
  </startup>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Core" publicKeyToken="b77a5c561934e089" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Common.Logging" publicKeyToken="af08829b84f0328e" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.1.0.0" newVersion="3.1.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>

**Comment by ftagliento** [comment]
<sipua srtp="Disabled" secureSignaling="0" logMessages="true" logLevel="5" traceAndDebug="false" autoAnswer="false" autoRecording="true" autoConference="false" maxCalls="5">
    <accounts>
    </accounts>
    <sipTransport type="tcp" Port="5080">
    </sipTransport>
    <networkSettings natInSDP="false" forceLooseRoute="false">
      <turn enabled="false" server="" type="tcp" userName="" password="" realm="" />
      <ice enabled="false" noRTCP="false" />
    </networkSettings>
    <media isVADEnabled="false" playbackDeviceId="7" captureDeviceId="5" />
  </sipua>

**Comment by ftagliento** [comment]
<sipua srtp="Disabled" secureSignaling="0" logMessages="true" logLevel="5" traceAndDebug="false" autoAnswer="false" autoRecording="true" autoConference="false" maxCalls="5">
    <accounts>
    </accounts>
    <sipTransport type="tcp" Port="5080">
    </sipTransport>
    <networkSettings natInSDP="false" forceLooseRoute="false">
      <turn enabled="false" server="" type="tcp" userName="" password="" realm="" />
      <ice enabled="false" noRTCP="false" />
    </networkSettings>
    <media isVADEnabled="false" playbackDeviceId="7" captureDeviceId="5" />
  </sipua>

**Comment by ftagliento** [comment]
"<sipua srtp="Disabled" secureSignaling="0" logMessages="true" logLevel="5" traceAndDebug="false" autoAnswer="false" autoRecording="true" autoConference="false" maxCalls="5">
    <accounts>
    </accounts>
    <sipTransport type="tcp" Port="5080">
    </sipTransport>
    <networkSettings natInSDP="false" forceLooseRoute="false">
      <turn enabled="false" server="" type="tcp" userName="" password="" realm="" />
      <ice enabled="false" noRTCP="false" />
    </networkSettings>
    <media isVADEnabled="false" playbackDeviceId="7" captureDeviceId="5" />
  </sipua>"

**Comment by ftagliento** [comment]
![immagine](https://cloud.githubusercontent.com/assets/12661935/25892240/085714d6-3574-11e7-9568-622b0aee015e.jpg)

**Comment by siniypin** [comment]
Please also try to capture the SIP trace to see what's going on there. You can turn the SIP logging on with this setting: https://gist.github.com/siniypin/7860029#file-app-config-L6

**Comment by siniypin** [comment]
`logLevel="5"` to be precise

**Comment by siniypin** [comment]
btw, you can try to change a SIP port to default value 5060, just in case =)

**Comment by ftagliento** [comment]
Using 5060 standard port nothing changed. Here the siptrace.

Thanks
[siptrace.txt](https://github.com/siniypin/pjsip4net/files/991109/siptrace.txt)

**Comment by siniypin** [comment]
Can you compare it to a sip trace of pjsua? Also upload it here please.

**Comment by ftagliento** [comment]
[siptrace.txt](https://github.com/siniypin/pjsip4net/files/992320/siptrace.txt)
[pjsua_siptrace.txt](https://github.com/siniypin/pjsip4net/files/992321/pjsua_siptrace.txt)

Yes, I started to compare many times the trace between pjsua and pjsi4net but not clear to me the reason. I attached them.

I have to say that testing the lib I was not able to register users correctly and after some debug I succeded modifying the file DefaultSipUserAgent.cs. Method Start I added this line 
localRegistry.SipTransport.Config.PublicAddress = myAddress;
before localRegistry.SipTransport.SetId(...)

Thanks
Francesco

**Comment by siniypin** [comment]
> I have to say that testing the lib I was not able to register users correctly and after some debug I succeded modifying the file DefaultSipUserAgent.cs. Method Start I added this line
localRegistry.SipTransport.Config.PublicAddress = myAddress;
That is a config setting, you don't have to modify a library to set it. You can do that either in confiog or in configuration code.

**Comment by ftagliento** [comment]
Yes, I tried to set PublicAddress  in the config file, but doesn't work.

```
<sipTransport type="tcp" Port="5063">
    <publicAddress>192.168.56.2</publicAddress>
</sipTransport>
```

**Comment by siniypin** [comment]
It has to be configured as an attribute:
```
<sipTransport type="tcp" Port="5063" BoundAddress="192.168.56.2" PublicAddress="192.168.56.2"/>
```

**Comment by ftagliento** [comment]
You are right, as attribute registrayion is ok but audio problem is still there :(

Francesco
