### ISSUE TITLE
Account problem

### ISSUE THREAD

**Issue by SenolBalaban** [siniypin/pjsip4net#73]
Hi 
This is a great Project.

My SIP Provider
Has an username, and a authenticationname
has a Domain and an Outbound Proxy.

if Install via nuget and start a console

and try to make acall with follwoing code

` static void Main(string[] args)
        {

            
            var ua = Configure.Pjsip4Net()
                .With(x => x.Config.AutoAnswer = false)
                .With(x => x.Config.OutboundProxies.Add("sip:fs1.ims.sipprovider.com"))
                .With(x=>x.Config.Credentials.Add(new NetworkCredential("authname@sipprovider.com", "password")))
                .Build()
                .Start();
            Console.ReadLine();

            ua.CallManager.MakeCall(ua.AccountManager.DefaultAccount, "555-5555");
            Console.ReadLine();
            ua.CallManager.HangupAll();
            ua.Destroy();
        }`
i get first this output and everything seems fine

>  00:47:48.103 os_core_win32.  pjlib 1.4 for win32 initialized
>  00:47:48.113 sip_endpoint.c  Creating endpoint instance...
>  00:47:48.117          pjlib  WinNT IOCP I/O Queue created (0761C078)
>  00:47:48.117 sip_endpoint.c  Module "mod-msg-print" registered
>  00:47:48.117 sip_transport.  Transport manager created.

but after hitting enter

I get following runtime error

> An unhandled exception of type 'System.ArgumentException' occurred in pjsip4net.Core.dll
> Additional information: Invariant is not TRUE

what could be the error?

Sincerely

**Comment by siniypin** [comment]
Hi, can you kindly post a stacktrace as well?

**Comment by siniypin** [comment]
I also think you shouldn't use a default account as long as the default is usually a local one (no registration).

**Comment by SenolBalaban** [comment]
bei pjsip4net.Core.Utils.SipUriParser..ctor(String sipUri) in c:\work\pjsip4net\pjsip4net.Core\Utils\SipUriParser.cs:Zeile 291.
   bei pjsip4net.Calls.DefaultCallManager.<>c__DisplayClasse.<MakeCall>b__d(ICallBuilder x) in c:\work\pjsip4net\pjsip4net\Calls\DefaultCallManager.cs:Zeile 117.
   bei pjsip4net.Calls.DefaultCallManager.MakeCall(Func`2 builder) in c:\work\pjsip4net\pjsip4net\Calls\DefaultCallManager.cs:Zeile 126.
   bei pjsip4net.Calls.DefaultCallManager.MakeCall(IAccount account, String destinationUri) in c:\work\pjsip4net\pjsip4net\Calls\DefaultCallManager.cs:Zeile 115.
   bei pj4SipCOnsole.Program.Main(String[] args) in D:\VS15\pj4SipCOnsole\pj4SipCOnsole\Program.cs:Zeile 29.
   bei System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   bei System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   bei Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   bei System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()

**Comment by SenolBalaban** [comment]
Hi
> I also think you shouldn't use a default account
Account is declared as internal so how do I create an Account?

If I try to create an Account within the App.aconfig I get 


> An unhandled exception of type 'Common.Logging.ConfigurationException' occurred in Common.Logging.dll
> 
> Additional information: Failed obtaining configuration for Common.Logging from configuration section 'common/logging'.
>

**Comment by siniypin** [comment]
Hello,

The `MakeCall` method accepts a destinationUrl string that has to conform to SIP address standard, i.e. you should have used a "5555-5555@sipprovider.domain" instead of "5555-555". SIP address grammar is described here: http://www.cs.columbia.edu/sip/SIPgrammar.html

I've no idea what is wrong with common.logging. Usually one have no problem with it, provided it is configured correctly. Try googling the error message. You can remove it whatsoever, if you need no logging. 
You can also create accounts programmatically: https://gist.github.com/siniypin/5951687 , - there are two options to create an account programmatically presented in that example.

Good luck.

**Comment by SenolBalaban** [comment]
Hi thx for nice reply

> The MakeCall method accepts a destinationUrl string that has to conform to SIP address standard,

My Sipprovider connects to the normal landline and mobilephones and I didn't knew this.

now I tried the example linked example

```
 public void Configure(IConfigurationContext context)
            {
                var registrar = "swisscom.ch";
                var accountId = new SipUriBuilder().AppendDomain("swisscom.ch").AppendExtension("username").ToString();
                var proxy = "fs1.ims.swisscom.ch";
                context.RegisterAccounts(new[]
                {
                    new AccountConfig()
                    {
                        RegUri = registrar,
                        Id =  accountId,
                        Credentials = new List<NetworkCredential>() {new NetworkCredential("authname", "password")},
                        Proxy = new List<string>() {proxy},IsDefault = true,
                        

                    },
                });
            }

```

getting at:

`   ua.Start();`

following errormesseage

> Choice stack is empty. Unable to fallback to another state.

stacktrace:
```
bei pjsip4net.Core.Utils.NfaWithBackTracking`2.PopChoice() in c:\work\pjsip4net\pjsip4net.Core\Utils\NfaWithBackTracking.cs:Zeile 70.
   bei pjsip4net.Core.Utils.NfaWithBackTracking`2.ComsumeAllInputSymbols(List`1 symbols) in c:\work\pjsip4net\pjsip4net.Core\Utils\NfaWithBackTracking.cs:Zeile 59.
   bei pjsip4net.Core.Utils.SipUriParser.ParseString(String sipUri) in c:\work\pjsip4net\pjsip4net.Core\Utils\SipUriParser.cs:Zeile 327.
   bei pjsip4net.Core.Utils.SipUriParser..ctor(String sipUri) in c:\work\pjsip4net\pjsip4net.Core\Utils\SipUriParser.cs:Zeile 292.
   bei pjsip4net.Accounts.Account.EndInit() in c:\work\pjsip4net\pjsip4net\Accounts\Account.cs:Zeile 345.
   bei pjsip4net.Core.Initializable.Initializer.Dispose() in c:\work\pjsip4net\pjsip4net.Core\Initializable.cs:Zeile 78.
   bei pjsip4net.DefaultSipUserAgent.Start() in c:\work\pjsip4net\pjsip4net\DefaultSipUserAgent.cs:Zeile 108.
   bei pjs4sipConsole2.Program.Main(String[] args) in D:\VS15\pjs4sipConsole2\pjs4sipConsole2\Program.cs:Zeile 56.
   bei System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   bei System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   bei Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   bei System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()



```

**Comment by siniypin** [comment]
Can you check that 
`new SipUriBuilder().AppendDomain("swisscom.ch").AppendExtension("username").IsValid` yields no errors? What should your sip account id look like in the end? sip:username@swisscom.ch ?

**Comment by siniypin** [comment]
@SenolBalaban Is there anything I can help with here? Is it solved?
