### ISSUE TITLE
I'm lost trying to figure out when "the other side" has ended the call on their end

### ISSUE THREAD

**Issue by BanditMcDougal** [siniypin/pjsip4net#74]
Like other have said, this is a great library; kudos to you for putting it together.

I'm working on something similar to [SIPp ](http://sipp.sourceforge.net/) but for .net (and maybe .net core, if I can get it to work...) using your library to handle the heavy lifting.  The ONLY issue I've run into thus far is I cannot, for the life of me, figure out how to tell if "the other side" of a phone call has ended the call.  Checking to see if a call is Active or has active media or the other method checks/properties I'm forgetting all come back "true" after the call was ended by the other side.  It also doesn't seem like the ChangedMediaState event from the Console example is getting raised in this case, either.

Please save my poor desk from where I keep banging my head?

**Comment by siniypin** [comment]
Hi, it is impossible to diagnose your problem without knowing at least some details. I usually ask to post a configuration (either.config file or your configuration code) plus a SIP trace to see what's going on there. In addition to that knowing your network and SIP server setup (if any) also proves to be useful. 
You can get a SIP messages logged if you set a logging level to 5 or higher.

**Comment by BanditMcDougal** [comment]
I appreciate the reply; I'll post that info later today.

**Comment by BanditMcDougal** [comment]
For the moment, I'm communicating with an Asterisk 13 server via VPN in my company's corp DC.  Nothing too odd there and I'm using other SIP-based tools without any real struggle (SIPp mentioned before, MicroSIP as a corp phone, and a few in-house phones that are backed by pjsip proper).

For the config, I'm using the following in the app.config:

`  <sipua srtp="Disabled" secureSignaling="0" logMessages="true" logLevel="5" traceAndDebug="false" autoAnswer="true" autoRecording="false" autoConference="false" maxCalls="950">  `
`    <accounts>`
`      <account accountId="sip:user@asteriskserver.subdomain.subdomain.company.net:5060" registrarUri="sip:user@asteriskserver.subdomain.subdomain.company.net:5060" userName="user" password="password" realm="*" isDefault="true" publishPresence="true" /> `
`    </accounts>`
`    <sipTransport type="udp" Port="5060" />`
`    <networkSettings natInSDP="true" forceLooseRoute="false">`
`      <!--<stun address="stun.stunprotocol.org"/>-->`
`      <turn enabled="false" server="asteriskserver.subdomain.subdomain.company.net" type="udp" userName="user" password="password" realm="" />`
`      <ice enabled="false" noRTCP="false" />`
`      <!--<proxies>`
`        <add address="sip:proxy.sipthor.net"/>`
`      </proxies>-->`
`    </networkSettings>`
`    <media isVADEnabled="true" playbackDeviceId="9" captureDeviceId="6" />`
`  </sipua>`

And then I'm using the example you provided from the Console app to build up the config:

`             var container = new WindsorContainer();`
`            var cfg = Configure.Pjsip4Net().With_CastleContainer(container).FromConfig();  `
`            ua = cfg.Build().Start();`

I had to duplicate the pjsip4net.Container.Castle .cs files since I couldn't find that library on nuget.

I'm attaching [siptrace.txt](https://github.com/siniypin/pjsip4net/files/1026751/siptrace.txt) from the latest attempt, as well.

Appreciate the help with this.

**Comment by siniypin** [comment]
Hey, thanks for sharing your code here.

There are a few peculiar things. However, that is what get my attention:
```
{{hung up from pjsip4net}}
2017-05-24 14:54:08,940 [11] DEBUG -  14:54:08.940   pjsua_core.c  TX 438 bytes Request msg BYE/cseq=18469 (tdta08DB74D8) to UDP 10.1.58.181:5060:
BYE sip:10.1.58.181:5060 SIP/2.0
Via: SIP/2.0/UDP 192.168.1.253:5060;rport;branch=z9hG4bKPjcad60ba7477346a499dc43aeb89229fa
Call-ID: 9cb90f04de5b45c4987aa0eacc9e5482
CSeq: 18469 BYE

--end msg--

2017-05-24 14:54:08,945 [11] DEBUG -  14:54:08.945   pjsua_core.c  TX 438 bytes Request msg BYE/cseq=18470 (tdta096C0108) to UDP 10.1.58.181:5060:
BYE sip:10.1.58.181:5060 SIP/2.0
Via: SIP/2.0/UDP 192.168.1.253:5060;rport;branch=z9hG4bKPj159e8d186c1841c9a0daabe0842fd9e1
Call-ID: 9cb90f04de5b45c4987aa0eacc9e5482
CSeq: 18470 BYE

--end msg--

...

2017-05-24 14:54:08,973 [11] INFO  -  14:54:08.973    pjsua_acc.c  Unregistration sent

2017-05-24 14:54:08,973 [11] DEBUG -  14:54:08.973   pjsua_core.c  Shutting down...

2017-05-24 14:54:08,973 [11] DEBUG -  14:54:08.973   pjsua_core.c  RX 462 bytes Response msg 200/BYE/cseq=18469 (rdata0699030C) from UDP 10.1.58.181:5060:
SIP/2.0 200 OK
Via: SIP/2.0/UDP 192.168.1.253:5060;rport=5060;received=10.1.200.216;branch=z9hG4bKPjcad60ba7477346a499dc43aeb89229fa
Call-ID: 9cb90f04de5b45c4987aa0eacc9e5482
CSeq: 18469 BYE
Server: Asterisk PBX 13.7.2

--end msg--

2017-05-24 14:54:08,974 [11] DEBUG - Call 0 DisconnectedInviteState
2017-05-24 14:54:08,975 [11] DEBUG - Call 0 disposed
2017-05-24 14:54:08,975 [11] DEBUG -  14:54:08.975  pjsua_media.c  Media session for call 0 is destroyed

2017-05-24 14:54:08,976 [11] DEBUG -  14:54:08.976   pjsua_core.c  RX 462 bytes Response msg 200/BYE/cseq=18470 (rdata0699030C) from UDP 10.1.58.181:5060:
SIP/2.0 200 OK
Via: SIP/2.0/UDP 192.168.1.253:5060;rport=5060;received=10.1.200.216;branch=z9hG4bKPj159e8d186c1841c9a0daabe0842fd9e1
Call-ID: 9cb90f04de5b45c4987aa0eacc9e5482
CSeq: 18470 BYE
Server: Asterisk PBX 13.7.2

--end msg--
```

The call has been hung up (the BYE request is sent twice, strangely enough) and a your endpoint has received a confirmation (twice). What did you expect to happen that did not? Does your endpoint send BYE requests and get nothing in response, or does it not send anything? What did you mean with `{{hung up from pjsip4net}}` comment, exactly? Did you call `Call.HangUp()` function or did you stop an entire host process? 

Or is there a problem on the other side? Does it not disconnect the call?

**Comment by BanditMcDougal** [comment]
> What did you mean with {{hung up from pjsip4net}} comment, exactly? Did you call Call.HangUp() function or did you stop an entire host process?

Since I could have multiple calls still going on, I use a Parallel.For effort to hang up any calls that _might_ still be in progress when I try to close the app:

            Parallel.For(0, callCount, i =>
                        {
                            try
                            {
                                ua.CallManager.GetCallById(i).Hangup();
                            }
                            catch (Exception e)
                            {
                                logger.Error(e);
                            }
                        });
            ua.Destroy(); 

Not the cleanest way to get things done I'm sure, but I'm still very, very much at the prototype/learning phase of this application.

> The call has been hung up (the BYE request is sent twice, strangely enough) and a your endpoint has received a confirmation (twice). What did you expect to happen that did not? Does your endpoint send BYE requests and get nothing in response, or does it not send anything?

That is odd...  I'll see if I can get some of the server-side messages from one of these test runs.  Basically, what I'm doing is throwing calls at our contact center system and confirming the routing, etc.  Sometimes I'm ending the call as a member of the contact center (the note about {{ other side hung up }} or something of that flavor is where that happened, and other times I'll exhaust a max talk time limit and end the call from the pjsip4net side.

When the app is done, I'm trying to hang everything up (noted above) in case I've not done something right, yet, while I'm learning the library.

**Comment by BanditMcDougal** [comment]
Worked with my engineering partner for a good chunk of the morning; looks like we ran into a NAT issue thanks to the introduction of the VPN into the mix.  Some changes were made at the asterisk end to have it reply back to where the actual SIP packets came from rather than the contact IP that was supplied and we're getting back "BYE" message as expected, now, which is great.

Is there something I should have done different with the config to avoid my localhost's IP getting used rather than the VPN's/interfaces IP?

Again, appreciate you being responsive; not many folks keep up with their older work anywhere close to this well.

**Comment by siniypin** [comment]
Hi, I'm glad you've nailed it down. It is my pleasure helping you guys to do real stuff with this library, although it get's even more complicated as I've got no Windows installation under my hands anymore.

The usage of callee's IP addresses in BYE requests was something I found 'peculiar' in this example. To be honest, I think there is nothing you could have done to avoid that, as I think that this problem is caused by a bug in an old pjsip dll that pjsip4net uses under the hood. I'd expect many of such problems to go away with an upgrade to a newer version of pjsip.

BTW, if you simply tear the user agent down with a `Destoy()` method, it would also disconnect all of the open calls in a normal way for you. https://gist.github.com/siniypin/5951687#file-createuawithaccounts-cs-L35

**Comment by siniypin** [comment]
Could you kindly share a change you've applied on Asterisk?

**Comment by BanditMcDougal** [comment]
Engineering partner tells me it was a fairly straight forward config option we'd never needed before:

https://wiki.asterisk.org/wiki/display/AST/Asterisk+12+Configuration_res_pjsip#Asterisk12Configuration_res_pjsip-endpoint_rewrite_contact
