### ISSUE TITLE
Capture and receive audio stream in realtime?

### ISSUE THREAD

**Issue by FordSoft** [siniypin/pjsip4net#77]
Hello! Thanks for your project. How can i capture and receive audio stream (no files) in realtime ?

**Comment by siniypin** [comment]
Hi,

I guess the simplest way would be to plug your own implementation of a sound port to  conference bridge:  
https://trac.pjsip.org/repos/wiki/media-flow  
http://www.pjsip.org/docs/latest-1/pjmedia/docs/html/group__PJMED__SND__PORT.htm
