### ISSUE TITLE
CreatePlaylistAndGetId string format

### ISSUE THREAD

**Issue by umairhaque** [siniypin/pjsip4net#78]
Guys,

I am facing an issue while passing the parameters to this method. 

As per method parameter, This method requires files names as string parameter but when I check the PJSIP documentation it requires the array of files names.

Any buddy has any info that how to pass multiple files in this parameter. I also tried by passing comma separated full path of the audio files but still, it did not work.

**Comment by siniypin** [comment]
Hi, 

A corresponding [method](https://github.com/siniypin/pjsip4net/blob/master/pjsip.Interop/Interop.cs#L13294) from pjsua v1.4 (that is the only underlying pjsua dll version currently supported) accepts just a single string reference. Therefore, pjsip4net can only pass a single string. However, I'm not sure whether it is a "feature" of pjsua v1.4 or an error in the autogenerated interop code.  
You can figure whether it is an error by inspecting pjsua.dll to see if an exported method signature corresponds to the one in interop code with tools like DependencyWalker.  
Let me know if you need any further support.
