### ISSUE TITLE
DTMF Received Event not working properly in More then one call

### ISSUE THREAD

**Issue by makwanaa** [siniypin/pjsip4net#79]
Hi
I registered user agent and add event handler for DTMF received event and made two calls simultaneously. calls connected successfully . Then pressed number digit form both calls but only from second call dtmf received, DTMF of first call not received.

**Comment by siniypin** [comment]
Hey @makwanaa, did you figure the problem out?

**Comment by makwanaa** [comment]
Hello  siniypin 
No I m not able to solve it. DTMF received only in one call.

**Comment by siniypin** [comment]
Can you collect SIP trace and post it here? You need to set a high log level in configuration in order to trace SIP messages in your log: https://gist.github.com/siniypin/7860029#file-app-config-L6
