### ISSUE TITLE
pjsip4net raspbian

### ISSUE THREAD

**Issue by skywalker1979** [siniypin/pjsip4net#84]
Hi,

i'm trying to use pjsip4net on a raspberry with raspbian and mono.
I'm getting this error:  (compiling on VS2013 and then moving exe to raspberry)

Is there an incompatibility?

Thanks.
Giulio

[New LWP 14452]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
0x76e96ef8 in __libc_waitpid (pid=14453, stat_loc=0x7e9311c8, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40
40      ../sysdeps/unix/sysv/linux/waitpid.c: File o directory non esistente.  (translation....missing file!!)
  Id   Target Id         Frame
  2    Thread 0x769ab430 (LWP 14452) "mono" 0x76e94a40 in do_futex_wait (isem=isem@entry=0x3181a4) at ../nptl/sysdeps/unix/sysv/linux/sem_wait.c:48
* 1    Thread 0x76f89000 (LWP 14451) "mono" 0x76e96ef8 in __libc_waitpid (pid=14453, stat_loc=0x7e9311c8, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40

Thread 2 (Thread 0x769ab430 (LWP 14452)):
#0  0x76e94a40 in do_futex_wait (isem=isem@entry=0x3181a4) at ../nptl/sysdeps/unix/sysv/linux/sem_wait.c:48
#1  0x76e94af4 in __new_sem_wait (sem=0x3181a4) at ../nptl/sysdeps/unix/sysv/linux/sem_wait.c:69
#2  0x00219f98 in mono_sem_wait ()
#3  0x0019091c in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

**Comment by siniypin** [comment]
Hi, skywalker1979.

Unfortunately, pjsip4net is not Mono compatible.

**Comment by skywalker1979** [comment]
ok..thanks....maybe in the future.
