### ISSUE TITLE
Getting call ID

### ISSUE THREAD

**Issue by bkraut** [siniypin/pjsip4net#85]
Hi,

I'd like to get CDR uniqueid from the current call. I tried with call.Id (ICall), but the Id is 0. Is there any way to get the CDR id?

Best,
Bojan

**Comment by siniypin** [comment]
Hi,
you can query a dialog call id from `Call. DialogId ` https://github.com/siniypin/pjsip4net/blob/master/pjsip4net/Calls/Call.cs#L118

**Comment by bkraut** [comment]
Hi,

Thank you. But as I've seen the DialogId is DialogId = "daeab28b1aa849d993a2c8a12b7b461a"
But in CDR table I het uniqueid like 1489580474.6

Best,
 Bojan

**Comment by siniypin** [comment]
You're right, my mistake. The CDR table you refer to is your exchange server's internal table, and frankly, I'm not even sure this information gets transferred to a client ever.
