### ISSUE TITLE
HangUp problem during Incomming call

### ISSUE THREAD

**Issue by Katargina** [siniypin/pjsip4net#88]
Hi,
We have problem with Incoming call termination. When We click on HangUp, the call finishes, but we don't get Disconnected state or re-registry failed (we don't understand what happend on server side) at once or couldn't finish call at all on the second time.
So after that we coludn't commit incoming and outgoing calls at all before we rmake reconnection.

When we commited outgoing calls all is OK.

We are using latest version of pjsip4net.

What could be the problem?
Or maybe you can tell us where we can take source code of library  version 0.2.0.28 where this error didn't appear.

Errors of Hang up processing during incoming call in attachment.

![error_sip1](https://user-images.githubusercontent.com/40266213/41409605-721e3754-6fdf-11e8-86b5-b45a21cea72c.jpg)
![error_sip2](https://user-images.githubusercontent.com/40266213/41409611-76738034-6fdf-11e8-8425-022ca23382f0.jpg)

**Comment by siniypin** [comment]
Hi, I've checked the NuGet and I spotted that there is a mess with versions. Older releases are marked with higher versions (see a screenshot attached). 
<img width="785" alt="screen shot 2018-06-16 at 11 36 35 pm" src="https://user-images.githubusercontent.com/318545/41502613-5f648a7e-71be-11e8-8ae7-b1518fffbca0.png">

You can either try and downgrade (think upgrade) to v. 0.2.0.28, or give me a time to bump a version to smth higher than v. 0.2.2. Please let me know, if that helps.

**Comment by siniypin** [comment]
I have removed v. 0.2.x from NuGet altogether. Please run `Update-Package -Id pjsip4net –reinstall` on your project.

**Comment by ArtMooStyle** [comment]
And what about update source on a github? As i understand the problem linked to pjproject issue:
https://github.com/pjsip/pjproject/commit/36f1782ec8ee0a72971aabde981dd30316384b25

Any chance to retrive inertop to current version?

**Comment by siniypin** [comment]
@ArtMooStyle I am not aware of the problem you linked to, sorry.  
Did you mean whether it is possible to update pjsip4net to support 2.x version line? The answer is, yes it is. However, it is beyond my capabilities. Please check out this discussion: https://github.com/siniypin/pjsip4net/issues/48#issuecomment-247756999

**Comment by siniypin** [comment]
@ArtMooStyle Did you link a correct issue?

**Comment by Katargina** [comment]
@siniypin Robert I think @ArtMooStyle talk about https://github.com/pjsip/pjproject/commit/36f1782ec8ee0a72971aabde981dd30316384b25#diff-aec3a7d6fdb15c0b6d0f7f1f6f7aa107 issue
Could you correct original sources for pjsua. dll and send us it or send us this sources with version which was used for pjsip4net v.0.2.0.28 and we fix it by ourself, please.

**Comment by siniypin** [comment]
I can't correct original sources of pjsua.dll, because a dll pjsip4net uses under the hood is a dll that has been compiled from a stable and very old version of pjsip sources (1.4 to be precise). 

You're more than welcome to develop an interop library that'd support the latest 1.x version of pjsip.  

v.0.2.0.28 is the latest version, ergo what you see in github is v.0.2.0.28.

**Comment by siniypin** [comment]
@Katargina do you still have an issue with terminating incoming calls?

**Comment by siniypin** [comment]
bump
I'm about to close this issue, unless you still have troubles disconnecting calls.
