### ISSUE TITLE
Cant Make Call From PjSip4Net Console App, Error: Value was to large or too small for an Int 32

### ISSUE THREAD

**Issue by appgurung** [siniypin/pjsip4net#93]
Have done all necessary steps but can make call from PjSip4Net console app. register command worked well and registeration was successful. But the make call command does not initate call to my cell phone.
![capture](https://user-images.githubusercontent.com/35873978/48339023-6b3d4e80-e667-11e8-9fbe-b18d28d7d73f.PNG)

Please see attached Image.
Your fast response will be appreciated.

**Comment by siniypin** [comment]
Hello,

unfortunately the screenshot you've attached explains nothing. Kindly invest a bit more time into elaborating what exactly your setup is (config, errors/exceptions, your registrar's type, example of how you call to your mobile, etc), if you want me to help you.

R

**Comment by appgurung** [comment]
Have been able to make it work. I can now make a sip call from the console program. My next challenge it how to stream a wav file to the remote party. I noticed that the program records file/call by default using the WavRecord class. How do it changed that to streaming wav file.

**Comment by appgurung** [comment]
I can see StartRecording function been called in Call function under DefaultCallBuilder. I dont want to record a call  but stream a file wav file which I already have. I will need your expert guidance on how to achieve this
![capture](https://user-images.githubusercontent.com/35873978/48366733-03125b00-e6af-11e8-9795-04edfb0aa36d.PNG)

**Comment by appgurung** [comment]
I went through some this link https://gist.github.com/siniypin/47326a9fd78af95a3ff7
But went I copied that missing sample into my code am getting error.
![capture](https://user-images.githubusercontent.com/35873978/48369591-496bb800-e6b7-11e8-85bd-4764a6f51d41.PNG)

**Comment by siniypin** [comment]
To disable recording, simply configure your user agent with AutoRecording=false. https://github.com/siniypin/pjsip4net/blob/master/pjsip4net.Core/Data/UaConfig.cs#L14

**Comment by siniypin** [comment]
Concerning you error - there isn't much I can help you with, you'll have to figure out your code yourself.

**Comment by appgurung** [comment]
Have solved it, thanks.
