### ISSUE TITLE
How do I know if can outgoing sip call is answered? 

### ISSUE THREAD

**Issue by appgurung** [siniypin/pjsip4net#94]
I want to know if an outgoing call is answered so that I stream a wav file. Is there any event in Program.cs in pjsip4net console that can help me?

**Comment by siniypin** [comment]
Yep, https://github.com/siniypin/pjsip4net/blob/master/pjsip4net/Interfaces/ICallManager.cs#L16

**Comment by appgurung** [comment]
Thanks for your help.
