### ISSUE TITLE
No component for supporting the service pjsip4net.Core.Interfaces.ApiProviders.IBasicApiProvider was found

### ISSUE THREAD

**Issue by appgurung** [siniypin/pjsip4net#95]
I decided to migrate the working console app to web api project. But am getting:
**No component for supporting the service pjsip4net.Core.Interfaces.ApiProviders.IBasicApiProvider was found** when ever it gets to line  **ua = cfg.Build().Start();**

Please assist. What am I missing or am not doing right.

**Comment by siniypin** [comment]
Make sure you copy pjsip.Interop.dll and pjsua.dll files to you bin folder.
https://github.com/siniypin/pjsip4net#interop-assembly-automatic-discovery

**Comment by siniypin** [comment]
https://github.com/siniypin/pjsip4net/blob/master/Tests/Integration/pjsip4net.Console/pjsip4net.Console.csproj#L121

**Comment by appgurung** [comment]
Thanks so much.
