### ISSUE TITLE
Am getting error pjsua_core.c bind error: Address already in use When I want to make multiple calls at the same time

### ISSUE THREAD

**Issue by appgurung** [siniypin/pjsip4net#96]
Am getting **PJSUA_core.c bind error: Address already in use** when I want to make multiple calls at the same time in the **console app**

How can I make multiple calls at the same time.

**Comment by siniypin** [comment]
Do you start a new UserAgent for every call?

**Comment by appgurung** [comment]
Yes I did. Is there anything wrong with that?

**Comment by siniypin** [comment]
> Address already in use

**Comment by siniypin** [comment]
You only need one user agent. It can handle multiple calls simultaneously.

**Comment by appgurung** [comment]
Thanks, One more thing. In hanging up a call what command am I expected to enter. Is it the call ID or what?
