### ISSUE TITLE
Pjsua_media.c Unable to open sound device: Invalid number of channels 469997

### ISSUE THREAD

**Issue by appgurung** [siniypin/pjsip4net#97]
Am getting **Pjsua_media.c Unable to open sound device: Invalid number of channels 469997**. What could be the issue? Am deploying the app into a windows server, and there is sound driver on the server. The console program works perfectly on my window 10 laptop.

**Comment by siniypin** [comment]
There is a problem with the driver, probably. Try to change a codec, maybe.
