### ISSUE TITLE
Cross talk during simultaneous call

### ISSUE THREAD

**Issue by appgurung** [siniypin/pjsip4net#98]
Hello @siniypin,
 When am streaming 2 different wav file during concurrent call between two people. When the first person answers the call, he gets is own wav file played to him, and the wav file of the second person, while the second person gets an empty call. Any reason for this? or is there something am not doing right? 

My Goal Is: I want to be able to play 2 different wav file to 2 different calls answered

Please help/guide me as usual...THANKS!!

**Comment by siniypin** [comment]
Maybe check out this documentation first https://www.pjsip.org/docs/latest-1/pjsip/docs/html/group__PJSUA__LIB__MEDIA.htm pjsip4net replicates this API rather literally.
